# Copyright 2026 KAITEN INC
# SPDX-License-Identifier: Apache-2.0

# Generated by scripts/generate_models.py from openapi/openapi.yaml. Do not edit by hand:
# change the contract (`task sync:openapi`) or the generator, then run `task generate`.

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, Literal

from pydantic import Field

from .._models import KaitenModel

__all__ = [
    "AggregationMethod",
    "AuditTrail",
    "BasicTargeting",
    "BasicVariant",
    "BooleanEntitlementValue",
    "Component",
    "ConfigEntitlementValue",
    "Connector",
    "ConnectorActivation",
    "ConnectorSettings",
    "ConnectorSettingsSchema",
    "ConnectorState",
    "Customer",
    "CustomerCreationRejected",
    "CustomerIntegration",
    "CustomerIntegrationResource",
    "DefaultVariant",
    "Deployment",
    "DeploymentZone",
    "Entitlement",
    "EntitlementGroup",
    "EntitlementGroupSummary",
    "EntitlementGroupUsage",
    "EntitlementType",
    "EntitlementUsage",
    "EntitlementValue",
    "ErrorDetail",
    "FeatureFlag",
    "FeatureFlagEvaluated",
    "FeatureFlagType",
    "Instance",
    "InstanceEntitlementCapExceeded",
    "InstanceEntitlementUsagePeriodRolledOver",
    "InstanceEntitlementUsageReportAccepted",
    "InstanceEntitlementUsageWarningThresholdReached",
    "InstanceEntitlementValueGet",
    "InstanceIntegration",
    "InstanceIntegrationResource",
    "InstanceLifecycleStageChanged",
    "InstanceStatus",
    "InstanceStatusChanged",
    "License",
    "LicenseEntitlement",
    "LicenseEntitlementType",
    "LicenseFamilyView",
    "LicenseLifecycleState",
    "LicenseType",
    "ManifestEnvelope",
    "ManifestFlag",
    "MetadataField",
    "MetadataFieldImpact",
    "MetadataFieldImpactSample",
    "MetadataFieldReordered",
    "MetadataResourceType",
    "NumberEntitlementValue",
    "PlainToken",
    "Problem",
    "Release",
    "ResetAnchor",
    "ResetPeriod",
    "RolloutDateTargeting",
    "RolloutDateVariant",
    "RolloutPercentageTargeting",
    "RolloutPercentageVariant",
    "RolloutStep",
    "Scope",
    "ServiceAccount",
    "SystemTokenIssuance",
    "Targeting",
    "Targetings",
    "Token",
    "UsageBehavior",
    "UsageReportStatus",
    "User",
    "Variant",
]


AggregationMethod = Literal["COUNT", "SUM", "AVERAGE", "MIN", "MAX", "LATEST"]
"""How each reported usage value folds into an entitlement's stored total."""

EntitlementType = Literal["BOOLEAN", "NUMBER", "CONFIG", "NUMBER_AI_CREDIT"]
"""The value type of an entitlement in the catalog."""

FeatureFlagType = Literal["boolean", "string", "number", "object"]
"""The value type of a feature flag's variants."""

InstanceStatus = Literal["HEALTHY", "DEGRADED", "INCIDENT", "MAINTENANCE"]
"""The operational status of an instance."""

LicenseEntitlementType = Literal["BOOLEAN", "NUMBER", "CONFIG"]
"""The value type of an entitlement granted by a license."""

LicenseLifecycleState = Literal["DRAFT", "PUBLISHED", "ARCHIVED"]
"""Whether a license version may be served: ``DRAFT`` before it goes on sale, ``PUBLISHED``
while it is on sale, ``ARCHIVED`` once it has been withdrawn.
"""

LicenseType = Literal["DEVELOPMENT", "TRIAL", "PAID", "COMMUNITY"]
"""The kind of a license."""

MetadataResourceType = Literal["DEPLOYMENT_ZONE", "INSTANCE"]
"""The resource a metadata field applies to."""

ResetAnchor = Literal["CALENDAR", "LICENSE_START"]
"""What a periodic usage window is aligned on."""

ResetPeriod = Literal["HOUR", "DAY", "WEEK", "MONTH", "YEAR"]
"""How often a periodic entitlement's usage resets."""

Scope = Literal[
    "read:components",
    "read:customers",
    "read:deployment_zones",
    "read:entitlements",
    "read:feature_flags",
    "read:instances",
    "read:licenses",
    "read:metadata_fields",
    "read:notifications",
    "read:organizations",
    "read:releases",
    "read:tokens",
    "read:webhooks",
    "write:components",
    "write:customers",
    "write:deployment_zones",
    "write:entitlements",
    "write:feature_flags",
    "write:instances",
    "write:licenses",
    "write:metadata_fields",
    "write:notifications",
    "write:organizations",
    "write:releases",
    "write:tokens",
    "write:webhooks",
]
"""A permission an organization credential can carry, ``read:<resource>`` or
``write:<resource>``; ``write`` implies ``read`` on the same resource.
"""

UsageBehavior = Literal["append", "set"]
"""How a usage report applies: ``append`` folds the value in, ``set`` overwrites it."""

UsageReportStatus = Literal["ACCEPTED", "REJECTED"]
"""Whether a usage report was persisted."""


class AuditTrail(KaitenModel):
    """One entry of an instance's audit trail."""

    event_name: str = Field(alias="eventName")
    """Event name (e.g. ENTITLEMENT_VALUE_GET)"""

    event_type: str = Field(alias="eventType")
    """Event type identifier (e.g. com.kaiten.instance.entitlement.v1.value_get)"""

    id: str
    """Unique audit trail entry ID"""

    instance_id: str | None = Field(default=None, alias="instanceId")
    """Instance UUID (present for instance-scoped events)"""

    instance_slug: str = Field(alias="instanceSlug")
    """Instance slug"""

    payload: Any | None = None
    """Event payload (JSON)"""

    timestamp: datetime
    """When the event occurred"""


class BasicTargeting(KaitenModel):
    """A targeting rule that serves one variant to every context its CEL rule matches."""

    name: str

    rule: str
    """CEL expression for basicTargeting evaluation"""

    type: Literal["basic"]

    variant: str


class BasicVariant(KaitenModel):
    """A default variant that always serves one named variant."""

    type: Literal["basic"]

    value: str


class BooleanEntitlementValue(KaitenModel):
    """A boolean entitlement value: whether a feature is included."""

    type: Literal["boolean"]
    """Value type discriminator"""

    value: bool
    """Boolean value"""


class Component(KaitenModel):
    """A versioned building block of your product, that releases are made of."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when the component was created"""

    created_by: User = Field(alias="createdBy")
    """User who created this component"""

    description: str | None = None
    """Description of the component"""

    id: str
    """Unique identifier for the component"""

    name: str
    """Name of the component"""

    previous_component_id: str | None = Field(default=None, alias="previousComponentId")
    """Reference to the previous version of this component"""

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. Auto-generated if not provided."""

    version: str
    """Version of the component"""


class ConfigEntitlementValue(KaitenModel):
    """A configuration entitlement value: a free-form object."""

    type: Literal["object"]
    """Value type discriminator"""

    value: dict[str, Any]
    """Object configuration value"""


class Connector(KaitenModel):
    """A connector registered with this Kaiten deployment."""

    created_at: datetime
    """Timestamp when connector was first registered"""

    entitlement_slug: str | None = None
    """Slug of the BOOLEAN entitlement a license must grant for an organization to activate
    this connector. Absent means the connector is ungated.
    """

    name: str
    """Stable connector identifier"""

    settings_schema: dict[str, Any]
    """JSON schema used to validate connector settings payloads"""

    updated_at: datetime
    """Timestamp when connector registration was last updated"""

    version: str
    """Registered connector version"""


class ConnectorActivation(KaitenModel):
    """An organization's activation of a connector."""

    activated_at: datetime = Field(alias="activatedAt")
    """When this organization first activated the connector"""

    connector_name: str = Field(alias="connectorName")
    """Stable connector identifier"""


class ConnectorSettings(KaitenModel):
    """An organization's settings for a connector."""

    connector_name: str
    """Stable connector identifier"""

    settings: dict[str, Any]
    """Connector settings payload"""


class ConnectorSettingsSchema(KaitenModel):
    """The JSON schema a connector's settings are validated against."""

    connector_name: str
    """Stable connector identifier"""

    json_schema: dict[str, Any] = Field(alias="schema")
    """JSON schema describing supported connector settings payload"""

    version: str
    """Registered connector version"""


class ConnectorState(KaitenModel):
    """Whether a connector is available, licensed and activated for this organization."""

    activated: bool
    """Whether this organization has turned the connector on"""

    activated_at: datetime | None = Field(default=None, alias="activatedAt")
    """When this organization activated the connector. Absent when it has not."""

    available: bool
    """Whether this deployment has the connector registered"""

    connector_name: str = Field(alias="connectorName")
    """Stable connector identifier"""

    entitled: bool
    """Whether this organization's licence includes the connector. True for an ungated connector."""

    version: str | None = None
    """Registered connector version. Absent when the connector is not available."""


class Customer(KaitenModel):
    """A customer of your organization: the end client instances are deployed for."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when the customer was created"""

    created_by: User = Field(alias="createdBy")
    """User who created this customer"""

    domain: str | None = None
    """Optional customer domain name"""

    external_customer_id: str | None = Field(default=None, alias="externalCustomerId")
    """Optional identifier for the customer in an external system"""

    id: str
    """Unique identifier for the customer"""

    integrations: dict[str, CustomerIntegration] | None = None
    """Integrations grouped by adapter name"""

    name: str
    """Name of the customer"""

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. Auto-generated if not provided."""

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when the customer was last updated"""

    updated_by: User = Field(alias="updatedBy")
    """User who last updated this customer"""


class CustomerCreationRejected(KaitenModel):
    """A customer creation refused because the organization reached its limit."""

    name: str

    reason: str

    slug: str


class CustomerIntegration(KaitenModel):
    """A customer's link to a record in a third-party system."""

    external_id: str
    """External identifier in the third-party adapter"""

    last_error: str | None = None
    """Last synchronization error message, if any"""

    metadata: dict[str, Any] | None = None
    """Adapter-specific integration metadata"""

    synced_at: datetime
    """Timestamp of the last synchronization with the adapter"""

    web_url: str | None = None
    """Absolute http(s) link to the record in the third-party system"""


class CustomerIntegrationResource(KaitenModel):
    """A customer as seen through one of its integrations."""

    domain: str | None = None
    """Optional customer domain name"""

    error: str | None = None
    """Last synchronization error for this integration, if any"""

    integration_metadata: dict[str, Any] = Field(alias="integrationMetadata")
    """Adapter-specific customer integration metadata"""

    name: str
    """Customer name"""

    slug: str
    """Customer slug"""

    web_url: str | None = Field(default=None, alias="webUrl")
    """Absolute http(s) link to the record in the third-party system"""


class Deployment(KaitenModel):
    """A release deployed to a deployment zone: an append-only history record."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when the deployment was recorded"""

    created_by: User = Field(alias="createdBy")
    """User who recorded this deployment"""

    deployment_zone_id: str = Field(alias="deploymentZoneId")
    """Deployment zone the release was deployed to"""

    id: str
    """Unique identifier for this deployment event"""

    release_id: str = Field(alias="releaseId")
    """Release that was deployed"""


class DeploymentZone(KaitenModel):
    """An environment instances run in, and the release currently deployed to it."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when the deployment zone was created"""

    created_by: User = Field(alias="createdBy")
    """User who created this deployment zone"""

    description: str
    """Description of the deployment zone"""

    id: str
    """Unique identifier for the deployment zone"""

    metadata: dict[str, Any] | None = None
    """Typed metadata for the deployment zone, validated against the org-scoped MetadataField
    schema
    """

    name: str
    """Name of the deployment zone"""

    release_id: str | None = Field(default=None, alias="releaseId")
    """Currently deployed release ID"""

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. Auto-generated if not provided."""

    type: str
    """Environment class of the deployment zone. Free-form: any value is stored as sent, but
    production, staging and development are the ones the console labels, and feature-flag
    targeting rules match on this field as __kaiten.deploymentZone.type.
    """

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when the deployment zone was last updated"""

    updated_by: User = Field(alias="updatedBy")
    """User who last updated the deployment zone"""


class Entitlement(KaitenModel):
    """A catalog entry: something a license can grant, and how its usage is measured."""

    aggregation_method: AggregationMethod | str | None = Field(
        default=None, alias="aggregationMethod"
    )
    """Method used to fold each reported usage value into the stored total (NUMBER only).
    Defaults to SUM.
    """

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when this entitlement was created"""

    description: str | None
    """Description of the entitlement"""

    display_order: int | None = Field(default=None, alias="displayOrder")
    """Sort order of this entitlement in customer-facing components (ascending). Defaults to 0."""

    entitlement_groups: list[EntitlementGroupSummary] | None = Field(
        default=None, alias="entitlementGroups"
    )
    """Groups associated with this entitlement"""

    group_slugs: list[str] | None = Field(default=None, alias="groupSlugs")
    """Groups associated with this entitlement, identified by slug"""

    icon: str | None = None
    """Optional icon, stored as a provider-namespaced token (provider:name). Decoupled from any
    specific icon library.
    """

    id: str
    """Unique identifier for the entitlement"""

    name: str
    """Name of the entitlement"""

    reset_anchor: ResetAnchor | str | None = Field(default=None, alias="resetAnchor")
    """Phase of the periodic usage window: CALENDAR (UTC calendar-aligned) or LICENSE_START
    (phased off the instance's license start date). Required exactly when resetPeriod is
    set; defaults to CALENDAR when omitted. Immutable once set.
    """

    reset_period: ResetPeriod | str | None = Field(default=None, alias="resetPeriod")
    """Cadence at which usage automatically resets for this NUMBER entitlement. NULL means a
    lifetime counter (default). Immutable once set -- a full-replace PUT must echo back the
    stored value.
    """

    sale_unit_factor: float | None = Field(default=None, alias="saleUnitFactor")
    """Number of base units one sale unit represents (1 sale unit = N base units)."""

    sale_unit_plural: str | None = Field(default=None, alias="saleUnitPlural")
    """Plural label of the unit this entitlement is sold in, when it differs from the base unit."""

    sale_unit_singular: str | None = Field(default=None, alias="saleUnitSingular")
    """Singular label of the unit this entitlement is sold in, when it differs from the base
    unit. Requires the base unit labels and the full sale unit trio (saleUnitSingular,
    saleUnitPlural, saleUnitFactor).
    """

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. Auto-generated if not provided."""

    type: EntitlementType | str | None = None
    """Type of the entitlement"""

    unit_plural: str | None = Field(default=None, alias="unitPlural")
    """Plural label of the base unit this entitlement is measured in (NUMBER type only). Must
    be provided together with unitSingular.
    """

    unit_singular: str | None = Field(default=None, alias="unitSingular")
    """Singular label of the base unit this entitlement is measured in (NUMBER type only). Must
    be provided together with unitPlural.
    """

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when this entitlement was last updated"""

    user_facing: bool | None = Field(default=None, alias="userFacing")
    """Whether this entitlement is displayed in customer-facing components (e.g. plan and
    pricing pages). Defaults to false.
    """

    warning_threshold_percent: int | None = Field(default=None, alias="warningThresholdPercent")
    """Percentage of the cap at which an early-warning event fires before the cap is reached. 0
    disables the warning (default).
    """


class EntitlementGroup(KaitenModel):
    """A named group of entitlements."""

    description: str | None
    """Description of the entitlement group"""

    id: str
    """Unique identifier for the entitlement group"""

    name: str
    """Name of the entitlement group"""

    slug: str | None = None
    """URL-friendly identifier, unique per organization. Auto-generated if not provided."""


class EntitlementGroupSummary(KaitenModel):
    """A reference to an entitlement group."""

    id: str
    """Unique identifier for the entitlement group"""

    name: str
    """Name of the entitlement group"""

    slug: str
    """URL-friendly identifier for the entitlement group"""


class EntitlementGroupUsage(KaitenModel):
    """One entitlement's grant and usage within a group, for one instance."""

    current_period_end: datetime | None = Field(default=None, alias="currentPeriodEnd")
    """End of the current usage window (exclusive). Null for a lifetime entitlement."""

    current_period_start: datetime | None = Field(default=None, alias="currentPeriodStart")
    """Start of the current usage window (inclusive). Null for a lifetime entitlement."""

    entitlement_id: str = Field(alias="entitlementId")
    """Entitlement ID"""

    entitlement_name: str = Field(alias="entitlementName")
    """Entitlement name"""

    entitlement_slug: str = Field(alias="entitlementSlug")
    """Entitlement slug"""

    entitlement_type: str = Field(alias="entitlementType")
    """Entitlement type"""

    license_value: EntitlementValue | None = Field(default=None, alias="licenseValue")
    """License limit value, discriminated by the 'type' field. Null when the license grants no
    value.
    """

    usage_value: EntitlementValue | None = Field(default=None, alias="usageValue")
    """Current usage value, discriminated by the 'type' field. Null when nothing has been
    reported yet.
    """


class EntitlementUsage(KaitenModel):
    """An instance's consumption of one entitlement, next to the grant it is measured against."""

    current_period_end: datetime | None = Field(default=None, alias="currentPeriodEnd")
    """End of the current usage window (exclusive). Null for a lifetime entitlement (no
    configured reset period).
    """

    current_period_start: datetime | None = Field(default=None, alias="currentPeriodStart")
    """Start of the current usage window (inclusive). Null for a lifetime entitlement (no
    configured reset period).
    """

    entitlement_id: str = Field(alias="entitlementId")
    """Unique identifier for the entitlement"""

    entitlement_slug: str = Field(alias="entitlementSlug")
    """URL-friendly identifier of the entitlement"""

    license_id: str = Field(alias="licenseId")
    """Unique identifier for the license to which this entitlement usage belongs"""

    license_slug: str = Field(alias="licenseSlug")
    """URL-friendly identifier of the license"""

    limit: EntitlementValue | None = None
    """License grant this usage is measured against, discriminated by the 'type' field. Null
    when the license grants no value; -1 means unlimited for a NUMBER entitlement.
    """

    value: EntitlementValue
    """Resolved entitlement value, discriminated by the 'type' field"""


class ErrorDetail(KaitenModel):
    """One validation problem inside an API error."""

    location: str | None = None
    """Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"""

    message: str | None = None
    """Error message text"""

    value: Any | None = None
    """The value at the given location"""


class FeatureFlag(KaitenModel):
    """A feature flag: its variants, targeting rules and default variant."""

    default_variant: DefaultVariant

    description: str | None

    enabled: bool

    event_name: str

    id: str

    metadata: dict[str, Any]

    name: str

    slug: str | None = None

    targetings: Targetings

    type: FeatureFlagType | str

    variants: list[Variant] | None


class FeatureFlagEvaluated(KaitenModel):
    """A feature flag evaluation, as reported to webhooks."""

    error_code: str | None = None
    """Set when the evaluation failed and the default was returned"""

    error_message: str | None = None
    """Human-readable detail accompanying error_code"""

    flag_id: str
    """Unique identifier of the evaluated flag"""

    flag_slug: str
    """URL-friendly identifier of the evaluated flag"""

    matched_rule_name: str | None = None
    """Name of the targeting rule that matched, when the reason is TARGETING_MATCH"""

    reason: str
    """Why the value resolved as it did"""

    variant: str | None = None
    """Name of the resolved variant, when the flag has one"""


class Instance(KaitenModel):
    """A deployment of your product for one customer, under one license."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when the instance was created"""

    created_by: User = Field(alias="createdBy")
    """User who created this instance"""

    customer_id: str = Field(alias="customerId")
    """ID of the customer associated with this instance"""

    customer_slug: str = Field(alias="customerSlug")
    """Slug of the customer associated with this instance"""

    deployment_zone_id: str | None = Field(default=None, alias="deploymentZoneId")
    """ID of the deployment zone associated with this instance (optional)"""

    deployment_zone_slug: str | None = Field(default=None, alias="deploymentZoneSlug")
    """Slug of the deployment zone associated with this instance (optional)"""

    description: str
    """Brief description of the instance"""

    end_license_date: datetime = Field(alias="endLicenseDate")
    """End date of the license for this instance"""

    id: str
    """Unique identifier for the instance"""

    integrations: dict[str, InstanceIntegration] | None = None
    """Integrations grouped by adapter name"""

    license_id: str = Field(alias="licenseId")
    """ID of the license version this instance is pinned to. An ARCHIVED version cannot be
    assigned, on create or by changing the license (CreateInstance.LicenseArchived,
    UpdateInstance.LicenseArchived); an instance already on a version that is archived later
    keeps it. A DRAFT version can be assigned, to try it before publishing.
    """

    license_slug: str = Field(alias="licenseSlug")
    """Slug of the license associated with this instance"""

    lifecycle_stage: str | None = Field(default=None, alias="lifecycleStage")
    """Commercial lifecycle stage of the instance (free-form; suggested: TRIAL, ACTIVE,
    AT_RISK, CHURNED)
    """

    metadata: dict[str, Any] | None = None
    """Metadata for the instance"""

    name: str
    """Name of the instance"""

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. Auto-generated if not provided."""

    start_license_date: datetime = Field(alias="startLicenseDate")
    """Start date of the license for this instance"""

    status: InstanceStatus | str | None = None
    """Operational status of the instance"""

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when the instance was last updated"""

    updated_by: User = Field(alias="updatedBy")
    """User who last updated this instance"""


class InstanceEntitlementCapExceeded(KaitenModel):
    """Usage crossed an entitlement's included value, within its allowance."""

    entitlement_slug: str
    """URL-friendly identifier of the entitlement"""

    overage: float
    """Amount by which usage exceeds the cap"""

    threshold: float
    """The entitlement cap"""

    value: float
    """Current usage value, including overage"""


class InstanceEntitlementUsagePeriodRolledOver(KaitenModel):
    """A periodic usage window closed and a new one opened."""

    closed_period_end: datetime | None

    closed_period_start: datetime | None

    entitlement_id: str

    entitlement_slug: str

    event_count: int

    instance_id: str

    is_synthetic: bool

    new_period_start: datetime

    value: float


class InstanceEntitlementUsageReportAccepted(KaitenModel):
    """The outcome of a usage report."""

    behavior: UsageBehavior | str
    """Report behavior: append folds the value into the stored total, set overwrites it"""

    entitlement_slug: str
    """URL-friendly identifier of the entitlement the usage was reported against"""

    event_count: int
    """Number of reports folded into the current usage window, including this one"""

    status: UsageReportStatus | str
    """Whether the report was persisted"""

    value: float
    """Value carried by the report"""


class InstanceEntitlementUsageWarningThresholdReached(KaitenModel):
    """Usage crossed an entitlement's warning threshold."""

    boundary: float
    """Usage value at which the warning fires (cap * warningThresholdPercent / 100)"""

    entitlement_slug: str
    """URL-friendly identifier of the entitlement"""

    threshold: float
    """The entitlement cap"""

    value: float
    """Current usage value"""


class InstanceEntitlementValueGet(KaitenModel):
    """An entitlement value read for an instance."""

    entitlement_id: str
    """Unique identifier for the entitlement"""

    entitlement_slug: str
    """URL-friendly identifier of the entitlement"""

    instance_id: str
    """Unique identifier for the instance the value was read for"""

    license_id: str
    """Unique identifier for the license carrying the entitlement"""

    organization_id: str
    """Unique identifier for the owning organization"""

    timestamp: datetime
    """When the value was read"""

    type: str
    """Discriminator of the resolved entitlement value"""

    value: EntitlementValue
    """Resolved entitlement value at read time"""


class InstanceIntegration(KaitenModel):
    """An instance's link to a record in a third-party system."""

    external_id: str
    """External identifier in the third-party adapter"""

    last_error: str | None = None
    """Last synchronization error message, if any"""

    metadata: dict[str, Any] | None = None
    """Adapter-specific integration metadata"""

    synced_at: datetime
    """Timestamp of the last synchronization with the adapter"""

    web_url: str | None = None
    """Absolute http(s) link to the record in the third-party system"""


class InstanceIntegrationResource(KaitenModel):
    """An instance as seen through one of its integrations."""

    customer_external_id: str | None = Field(default=None, alias="customerExternalId")
    """External identifier of the related customer in the same adapter"""

    deployment_zone_id: str | None = Field(default=None, alias="deploymentZoneId")
    """Deployment zone ID"""

    description: str
    """Instance description"""

    end_license_date: datetime = Field(alias="endLicenseDate")
    """License end date"""

    error: str | None = None
    """Last synchronization error for this integration, if any"""

    integration_metadata: dict[str, Any] = Field(alias="integrationMetadata")
    """Adapter-specific instance integration metadata"""

    license_id: str = Field(alias="licenseId")
    """License ID"""

    name: str
    """Instance name"""

    slug: str
    """Instance slug"""

    start_license_date: datetime = Field(alias="startLicenseDate")
    """License start date"""

    web_url: str | None = Field(default=None, alias="webUrl")
    """Absolute http(s) link to the record in the third-party system"""


class InstanceLifecycleStageChanged(KaitenModel):
    """An instance's commercial lifecycle stage changed."""

    changed_by: str

    instance_id: str

    new_lifecycle_stage: str | None

    previous_lifecycle_stage: str | None


class InstanceStatusChanged(KaitenModel):
    """An instance's operational status changed."""

    changed_by: str

    instance_id: str

    new_status: InstanceStatus | str

    previous_status: InstanceStatus | str


class License(KaitenModel):
    """A version of a license family: one set of entitlement grants, with its lifecycle state."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when this license was created"""

    description: str
    """Detailed description of the license capabilities and restrictions"""

    family_id: str | None = Field(default=None, alias="familyId")
    """Identifier of the license family this license is a version of. Stable across renames and
    new versions: two licenses sharing it are the same product. Always present in responses.
    On create, optional: names the family this license is a new version of, as familySlug
    does by slug; omit both to create a new family. On update, optional and must be the
    license's own family: a version cannot move between families
    (UpdateLicense.FamilyNotReassignable).
    """

    family_slug: str | None = Field(default=None, alias="familySlug")
    """Write-only on create: slug of the family this license is a new version of. familyId
    names the same family by identifier; sent together they must agree. Omit both to create
    a new family, of which this license becomes version 1. Never returned -- see familyId.
    Refused on update: a version cannot move between families.
    """

    id: str
    """Unique identifier for the license"""

    is_default: bool = Field(alias="isDefault")
    """Whether this version is the one its family puts forward: at most one version per family,
    and only a PUBLISHED one (CreateLicense.DefaultMustBePublished,
    UpdateLicense.DefaultMustBePublished). Resolution hands it out ahead of the highest-
    numbered published version, so it keeps being served when a newer version is published.
    Setting it takes the flag from the family's previous default, which gets a
    LICENSE_UPDATED event of its own. On update, sending false unsets it; the default cannot
    be archived until another version takes its place or the flag is unset
    (ArchiveLicense.DefaultMustBePublished).
    """

    lifecycle_state: LicenseLifecycleState | str | None = Field(
        default=None, alias="lifecycleState"
    )
    """Whether this version may be served. Always present in responses. Optional on create,
    where it is DRAFT or PUBLISHED and PUBLISHED when omitted; ARCHIVED is refused
    (CreateLicense.LifecycleStateNotSettable), since a version is archived by withdrawing it
    from sale. After that it changes only through publish-license (DRAFT to PUBLISHED),
    archive-license (PUBLISHED to ARCHIVED) and unarchive-license (ARCHIVED to PUBLISHED);
    update accepts the stored state and refuses any other
    (UpdateLicense.LifecycleStateNotSettable). Only a PUBLISHED version can be the family's
    default. An ARCHIVED version cannot be assigned to an instance
    (CreateInstance.LicenseArchived, UpdateInstance.LicenseArchived); instances already on
    it keep it.
    """

    name: str
    """Display name of the license"""

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. When omitted, a new version
    of an existing family takes {familySlug}-v{version}, and any other license gets one
    generated from its name. A license that opens a new family gives the family its slug.
    """

    type: LicenseType | str
    """Type of the license determining its capabilities and restrictions"""

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when this license was last updated"""

    version: str
    """Version of the license within its family, assigned by the server when the version is
    created and never changed afterwards: the version's derived slug
    ({familySlug}-v{version}, see slug) is built from it. A number is never reused within a
    family, even after its version is deleted. Create refuses any value
    (CreateLicense.VersionNotSettable); update accepts only the stored one, so a
    representation can be written back as it was read (UpdateLicense.VersionNotSettable).
    """

    version_name: str | None = Field(default=None, alias="versionName")
    """Optional human-readable name for the license version. Defaults to "Version - <version>"."""


class LicenseEntitlement(KaitenModel):
    """A grant: the value a license gives one entitlement, and how it is enforced."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when this entitlement was created"""

    created_by: User = Field(alias="createdBy")
    """User who created this entitlement"""

    entitlement_groups: list[EntitlementGroupSummary] | None = Field(
        default=None, alias="entitlementGroups"
    )
    """Groups associated with this entitlement"""

    entitlement_name: str = Field(alias="entitlementName")
    """Name of the entitlement feature or service"""

    entitlement_slug: str | None = Field(default=None, alias="entitlementSlug")
    """URL-friendly identifier for the entitlement"""

    entitlement_type: LicenseEntitlementType | str | None = Field(
        default=None, alias="entitlementType"
    )
    """Type of entitlement (BOOLEAN, NUMBER, or CONFIG)"""

    license_id: str = Field(alias="licenseId")
    """Unique identifier for the license this entitlement belongs to"""

    license_slug: str = Field(alias="licenseSlug")
    """URL-friendly identifier for the license this entitlement belongs to"""

    limit_cap_exceeded_overage_percent: int | None = Field(
        default=None, alias="limitCapExceededOveragePercent"
    )
    """Derives this grant's enforcement from its own numeric value: -1 when the value is
    unlimited (no cap, no overage); otherwise 0 rejects usage above the value (hard limit)
    and a positive percentage allows usage to exceed it by that much before being rejected
    (soft limit). Null for non-numeric (BOOLEAN/CONFIG) grants.
    """

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when this entitlement was last updated"""

    updated_by: User = Field(alias="updatedBy")
    """User who last updated this entitlement"""

    value: EntitlementValue
    """Typed entitlement value. Supported shapes: {type:number,value:number},
    {type:boolean,value:boolean}, {type:object,value:{...}}
    """


class LicenseFamilyView(KaitenModel):
    """A license family -- the product -- resolved to one of its versions."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when this family was created"""

    current_version: License | None = Field(default=None, alias="currentVersion")
    """The version this read is about. By default the version the family resolves to: its
    default version if it has one, otherwise its highest-numbered PUBLISHED version. Under
    ?version=N it is the version asked for instead, whatever its lifecycle state. Absent
    when the family has no PUBLISHED version, which only a list or an include=versions read
    returns.
    """

    id: str
    """Unique identifier for the license family"""

    slug: str
    """URL-friendly identifier of the family, unique per organization and stable across renames
    and new versions. Deleting the family's last version deletes the family and frees the
    slug.
    """

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when a version was last added to this family, or when the family was created.
    Renames, lifecycle moves and default changes update the versions' own updatedAt, not
    this one.
    """

    version_count: int = Field(alias="versionCount")
    """Number of versions in this family, whatever their lifecycle state"""

    versions: list[License] | None = None
    """Every version of the family, oldest first. Only returned when explicitly requested with
    include=versions, and then never null: a family always has at least one version.
    """


class ManifestEnvelope(KaitenModel):
    flags: list[ManifestFlag] | None


class ManifestFlag(KaitenModel):
    """One flag of the OpenFeature manifest."""

    default_value: Any = Field(alias="defaultValue")

    description: str | None = None

    key: str

    name: str | None = None

    type: str


class MetadataField(KaitenModel):
    """A typed field an organization declares on its instances or deployment zones."""

    archived_at: datetime | None = Field(default=None, alias="archivedAt")
    """Timestamp when the field was archived (soft delete). Absent if active."""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when the field was created"""

    created_by: User = Field(alias="createdBy")
    """User who created this field"""

    display_order: int | None = Field(default=None, alias="displayOrder")
    """Sort order in the admin UI; ties are broken by createdAt ASC. Settable only through POST
    /metadata-fields/reorder; never echoed back on update.
    """

    id: str
    """Unique identifier"""

    json_schema: dict[str, Any] = Field(alias="jsonSchema")
    """JSON Schema 2020-12 document describing the value space. Example:
    {"type":"string","enum":["a","b"]}
    """

    key: str
    """Stable identifier, unique per (organization, resource type) on non-archived rows.
    Immutable after creation; update must echo back the stored value.
    """

    label: str
    """Human-readable label shown in the admin UI"""

    resource_type: MetadataResourceType | str = Field(alias="resourceType")
    """Resource type this field applies to. Immutable after creation; update must echo back the
    stored value.
    """

    updated_at: datetime = Field(alias="updatedAt")
    """Timestamp when the field was last updated"""

    updated_by: User = Field(alias="updatedBy")
    """User who last updated this field"""


class MetadataFieldImpact(KaitenModel):
    """What a candidate metadata field schema would invalidate."""

    count: int
    """Number of resources whose stored value for this field would no longer satisfy the
    candidate schema
    """

    samples: list[MetadataFieldImpactSample] | None
    """Up to 5 impacted resources, for display"""


class MetadataFieldImpactSample(KaitenModel):
    """A resource a metadata field schema change would invalidate."""

    name: str
    """Resource display name"""

    slug: str
    """Resource slug"""


class MetadataFieldReordered(KaitenModel):
    """Metadata fields were given a new display order."""

    ids: list[str] | None
    """Metadata field ids in their new display order"""


class NumberEntitlementValue(KaitenModel):
    """A numeric entitlement value: a quota, or an amount consumed."""

    event_count: int | None = None
    """Number of events accumulated (server-computed)"""

    type: Literal["number"]
    """Value type discriminator"""

    value: float
    """Numeric value"""


class PlainToken(KaitenModel):
    """A token together with its plaintext secret, which the API returns exactly once."""

    created_at: datetime = Field(alias="createdAt")

    created_by: User = Field(alias="createdBy")

    expires_at: datetime | None = Field(default=None, alias="expiresAt")

    id: str | None = None

    name: str

    revoked_at: datetime | None = Field(default=None, alias="revokedAt")

    revoked_by: User | None = Field(default=None, alias="revokedBy")

    scopes: list[str] | None

    service_account_id: str | None = Field(default=None, alias="serviceAccountId")

    slug: str | None = None
    """Optional URL-friendly identifier, unique per service account. Auto-generated if not
    provided.
    """

    token: str | None = None


class Problem(KaitenModel):
    """An RFC 9457 problem document, which every API error carries."""

    code: str | None = None
    """Stable, machine-readable error code."""

    detail: str | None = None
    """A human-readable explanation specific to this occurrence of the problem."""

    error_id: str | None = Field(default=None, alias="errorId")
    """Correlation id for the server-side log entry describing the withheld cause."""

    errors: list[ErrorDetail] | None = None
    """Optional list of individual error details"""

    instance: str | None = None
    """A URI reference that identifies the specific occurrence of the problem."""

    status: int | None = None
    """HTTP status code"""

    title: str | None = None
    """A short, human-readable summary of the problem type. This value should not change
    between occurrences of the error.
    """

    type: str | None = None
    """A URI reference to human-readable documentation for the error."""


class Release(KaitenModel):
    """An immutable, versioned set of components."""

    component_ids: list[str] | None = Field(default=None, alias="componentIds")
    """List of component IDs to link to this release"""

    components: list[Component] | None = None
    """List of components included in this release, fixed at creation"""

    created_at: datetime = Field(alias="createdAt")
    """Timestamp when the release was created"""

    created_by: User = Field(alias="createdBy")
    """User who created this release"""

    description: str | None = None
    """Description of the release"""

    id: str
    """Unique identifier for the release"""

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. Auto-generated if not provided."""

    version: str
    """Version of the release"""


class RolloutDateTargeting(KaitenModel):
    """A targeting rule that shifts traffic between variants over a date range."""

    end: RolloutStep

    name: str

    rule: str
    """CEL expression for basicTargeting evaluation"""

    start: RolloutStep

    type: Literal["rollout_date"]


class RolloutDateVariant(KaitenModel):
    """A default variant that shifts traffic between variants over a date range."""

    end: RolloutStep

    start: RolloutStep

    type: Literal["rollout_date"]


class RolloutPercentageTargeting(KaitenModel):
    """A targeting rule that splits the contexts it matches between variants."""

    distribution: dict[str, int]

    name: str

    rule: str
    """CEL expression for basicTargeting evaluation"""

    type: Literal["rollout_percentage"]


class RolloutPercentageVariant(KaitenModel):
    """A default variant that splits traffic between variants by weight."""

    distribution: dict[str, int]

    type: Literal["rollout_percentage"]


class RolloutStep(KaitenModel):
    """One end of a date-based rollout."""

    date: datetime

    percentage: int

    variant: str


class ServiceAccount(KaitenModel):
    """A machine identity inside an organization, owning API tokens."""

    created_at: datetime | None = Field(default=None, alias="createdAt")

    created_by: User | None = Field(default=None, alias="createdBy")

    external_id: str | None = Field(default=None, alias="externalId")

    id: str | None = None

    name: str

    slug: str | None = None
    """Optional URL-friendly identifier, unique per organization. Auto-generated if not provided."""

    tokens: list[Token] | None


class SystemTokenIssuance(KaitenModel):
    """A platform credential minted a token inside this organization."""

    credential_kind: str = Field(alias="credentialKind")
    """Credential class that performed the mint; "platform" is the system:kaiten identity"""

    expires_at: datetime | None = Field(default=None, alias="expiresAt")
    """Absent when the minted credential does not expire"""

    issued_at: datetime = Field(alias="issuedAt")
    """When the credential was minted"""

    issued_token_id: str = Field(alias="issuedTokenId")
    """The credential that was minted"""

    name: str
    """Human-readable label the caller gave the minted credential"""

    platform_token_id: str = Field(alias="platformTokenId")
    """Platform credential that performed the mint; revoking it revokes everything it issued"""

    scopes: list[str] | None
    """Scopes granted to the minted credential"""

    slug: str
    """Server-assigned identifier of the minted credential"""


class Token(KaitenModel):
    """A token's metadata. Never its secret."""

    created_at: datetime = Field(alias="createdAt")

    created_by: User = Field(alias="createdBy")

    expires_at: datetime | None = Field(default=None, alias="expiresAt")

    id: str | None = None

    name: str

    revoked_at: datetime | None = Field(default=None, alias="revokedAt")

    revoked_by: User | None = Field(default=None, alias="revokedBy")

    scopes: list[str] | None

    service_account_id: str | None = Field(default=None, alias="serviceAccountId")

    slug: str | None = None
    """Optional URL-friendly identifier, unique per service account. Auto-generated if not
    provided.
    """


class User(KaitenModel):
    """A reference to the user behind an action."""

    id: str
    """ID of the user"""

    name: str | None = None
    """Name of the user"""


class Variant(KaitenModel):
    """One possible value of a feature flag."""

    description: str

    name: str

    value: Any


DefaultVariant = Annotated[
    BasicVariant | RolloutDateVariant | RolloutPercentageVariant, Field(discriminator="type")
]
"""What a feature flag serves when no targeting rule matches, discriminated by ``type``."""

EntitlementValue = Annotated[
    NumberEntitlementValue | BooleanEntitlementValue | ConfigEntitlementValue,
    Field(discriminator="type"),
]
"""A typed entitlement value, discriminated by ``type``: a number, a boolean or a config object."""

Targeting = Annotated[
    BasicTargeting | RolloutDateTargeting | RolloutPercentageTargeting, Field(discriminator="type")
]
"""One targeting rule of a feature flag, discriminated by ``type``."""

Targetings = list[Targeting] | None
"""A feature flag's targeting rules, evaluated in order; the first match wins."""


for _model in (
    AuditTrail,
    BasicTargeting,
    BasicVariant,
    BooleanEntitlementValue,
    Component,
    ConfigEntitlementValue,
    Connector,
    ConnectorActivation,
    ConnectorSettings,
    ConnectorSettingsSchema,
    ConnectorState,
    Customer,
    CustomerCreationRejected,
    CustomerIntegration,
    CustomerIntegrationResource,
    Deployment,
    DeploymentZone,
    Entitlement,
    EntitlementGroup,
    EntitlementGroupSummary,
    EntitlementGroupUsage,
    EntitlementUsage,
    ErrorDetail,
    FeatureFlag,
    FeatureFlagEvaluated,
    Instance,
    InstanceEntitlementCapExceeded,
    InstanceEntitlementUsagePeriodRolledOver,
    InstanceEntitlementUsageReportAccepted,
    InstanceEntitlementUsageWarningThresholdReached,
    InstanceEntitlementValueGet,
    InstanceIntegration,
    InstanceIntegrationResource,
    InstanceLifecycleStageChanged,
    InstanceStatusChanged,
    License,
    LicenseEntitlement,
    LicenseFamilyView,
    ManifestEnvelope,
    ManifestFlag,
    MetadataField,
    MetadataFieldImpact,
    MetadataFieldImpactSample,
    MetadataFieldReordered,
    NumberEntitlementValue,
    PlainToken,
    Problem,
    Release,
    RolloutDateTargeting,
    RolloutDateVariant,
    RolloutPercentageTargeting,
    RolloutPercentageVariant,
    RolloutStep,
    ServiceAccount,
    SystemTokenIssuance,
    Token,
    User,
    Variant,
):
    _model.model_rebuild()
del _model
