# Copyright 2026 KAITEN INC
# SPDX-License-Identifier: Apache-2.0

# Generated by scripts/generate_models.py from openapi/platform-openapi.yaml. Do not edit by hand:
# change the contract (`task sync:openapi`) or the generator, then run `task generate`.

from __future__ import annotations

from datetime import datetime

from pydantic import Field

from .._models import KaitenModel

__all__ = [
    "Organization",
    "PlatformCredential",
]


class Organization(KaitenModel):
    """A Kaiten organization: a tenant."""

    external_id: str
    """External identifier for the organization, used for integration with external systems"""

    id: str
    """Unique identifier for the organization"""

    name: str
    """Display name of the organization"""


class PlatformCredential(KaitenModel):
    """The platform credential (``ksm_...``) a platform client authenticates with."""

    created_at: datetime = Field(alias="createdAt")

    credential_kind: str = Field(alias="credentialKind")
    """Credential class of the calling token"""

    expires_at: datetime | None = Field(default=None, alias="expiresAt")
    """Absent when the credential does not expire"""

    id: str

    name: str

    scopes: list[str] | None

    slug: str

    subject: str
    """External id of the platform identity this credential authenticates"""


for _model in (
    Organization,
    PlatformCredential,
):
    _model.model_rebuild()
del _model
