# Copyright 2026 KAITEN INC
# SPDX-License-Identifier: Apache-2.0

# Generated by scripts/generate_models.py from openapi/openapi.yaml. Do not edit by hand:
# change the contract (`task sync:openapi`) or the generator, then run `task generate`.

"""The events Kaiten delivers to webhook endpoints, one model per published contract."""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import Field

from .._models import KaitenModel
from ._core import (
    Component,
    Customer,
    CustomerCreationRejected,
    Deployment,
    DeploymentZone,
    Entitlement,
    EntitlementGroup,
    EntitlementUsage,
    FeatureFlag,
    FeatureFlagEvaluated,
    Instance,
    InstanceEntitlementCapExceeded,
    InstanceEntitlementUsagePeriodRolledOver,
    InstanceEntitlementUsageReportAccepted,
    InstanceEntitlementUsageWarningThresholdReached,
    InstanceEntitlementValueGet,
    InstanceLifecycleStageChanged,
    InstanceStatusChanged,
    License,
    LicenseEntitlement,
    LicenseFamilyView,
    MetadataField,
    MetadataFieldReordered,
    Release,
    SystemTokenIssuance,
)

__all__ = [
    "WEBHOOK_EVENTS",
    "ComponentCreatedEvent",
    "ComponentDeletedEvent",
    "ComponentUpdatedEvent",
    "CustomerCreatedEvent",
    "CustomerCreationRejectedEvent",
    "CustomerDeletedEvent",
    "CustomerUpdatedEvent",
    "DeploymentZoneCreatedEvent",
    "DeploymentZoneDeletedEvent",
    "DeploymentZoneUpdatedEvent",
    "EntitlementCreatedEvent",
    "EntitlementDeletedEvent",
    "EntitlementGroupCreatedEvent",
    "EntitlementGroupDeletedEvent",
    "EntitlementGroupUpdatedEvent",
    "EntitlementUpdatedEvent",
    "FeatureFlagCreatedEvent",
    "FeatureFlagDeletedEvent",
    "FeatureFlagEvaluatedEvent",
    "FeatureFlagUpdatedEvent",
    "InstanceCreatedEvent",
    "InstanceDeletedEvent",
    "InstanceDeployedEvent",
    "InstanceEntitlementCapExceededEvent",
    "InstanceEntitlementUsagePeriodRolledOverEvent",
    "InstanceEntitlementUsageReachedEvent",
    "InstanceEntitlementUsageReportAcceptedEvent",
    "InstanceEntitlementUsageReportRejectedEvent",
    "InstanceEntitlementUsageWarningThresholdReachedEvent",
    "InstanceEntitlementValueGetEvent",
    "InstanceLifecycleStageChangedEvent",
    "InstanceMigratedEvent",
    "InstanceStatusChangedEvent",
    "InstanceUpdatedEvent",
    "LicenseArchivedEvent",
    "LicenseCreatedEvent",
    "LicenseDeletedEvent",
    "LicenseEntitlementAssignedEvent",
    "LicenseEntitlementUnassignedEvent",
    "LicenseEntitlementUpdatedEvent",
    "LicenseFamilyCreatedEvent",
    "LicenseFamilyDeletedEvent",
    "LicenseFamilyUpdatedEvent",
    "LicensePublishedEvent",
    "LicenseUnarchivedEvent",
    "LicenseUpdatedEvent",
    "MetadataFieldArchivedEvent",
    "MetadataFieldCreatedEvent",
    "MetadataFieldReorderedEvent",
    "MetadataFieldUnarchivedEvent",
    "MetadataFieldUpdatedEvent",
    "ReleaseCreatedEvent",
    "ReleaseDeletedEvent",
    "ReleaseDeployedEvent",
    "SystemOrganizationTokenIssuedEvent",
    "WebhookEvent",
]


class ComponentCreatedEvent(KaitenModel):
    """Triggered when a new component is created. Delivered as
    ``com.kaiten.component.v1.created``.
    """

    name: Literal["COMPONENT_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.component.v1.created"]
    """The event type: what tells one event from another."""

    data: Component
    """What the event is about."""


class ComponentDeletedEvent(KaitenModel):
    """Triggered when a component is deleted. Delivered as ``com.kaiten.component.v1.deleted``."""

    name: Literal["COMPONENT_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.component.v1.deleted"]
    """The event type: what tells one event from another."""

    data: Component
    """What the event is about."""


class ComponentUpdatedEvent(KaitenModel):
    """Triggered when a component is updated or auto-versioned. Delivered as
    ``com.kaiten.component.v1.updated``.
    """

    name: Literal["COMPONENT_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.component.v1.updated"]
    """The event type: what tells one event from another."""

    data: Component
    """What the event is about."""


class CustomerCreatedEvent(KaitenModel):
    """Triggered when a new customer is created. Delivered as ``com.kaiten.customer.v1.created``."""

    name: Literal["CUSTOMER_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.customer.v1.created"]
    """The event type: what tells one event from another."""

    data: Customer
    """What the event is about."""


class CustomerCreationRejectedEvent(KaitenModel):
    """Triggered when a customer creation is refused because the organization has reached its
    customer entitlement cap. No customer is created. Delivered as
    ``com.kaiten.customer.v1.creation_rejected``.
    """

    name: Literal["CUSTOMER_CREATION_REJECTED"]
    """The event name."""

    type: Literal["com.kaiten.customer.v1.creation_rejected"]
    """The event type: what tells one event from another."""

    data: CustomerCreationRejected
    """What the event is about."""


class CustomerDeletedEvent(KaitenModel):
    """Triggered when a customer is deleted. Delivered as ``com.kaiten.customer.v1.deleted``."""

    name: Literal["CUSTOMER_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.customer.v1.deleted"]
    """The event type: what tells one event from another."""

    data: Customer
    """What the event is about."""


class CustomerUpdatedEvent(KaitenModel):
    """Triggered when a customer is updated. Delivered as ``com.kaiten.customer.v1.updated``."""

    name: Literal["CUSTOMER_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.customer.v1.updated"]
    """The event type: what tells one event from another."""

    data: Customer
    """What the event is about."""


class DeploymentZoneCreatedEvent(KaitenModel):
    """Triggered when a new deployment zone is created. Delivered as
    ``com.kaiten.deployment_zone.v1.created``.
    """

    name: Literal["DEPLOYMENT_ZONE_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.deployment_zone.v1.created"]
    """The event type: what tells one event from another."""

    data: DeploymentZone
    """What the event is about."""


class DeploymentZoneDeletedEvent(KaitenModel):
    """Triggered when a deployment zone is deleted. Delivered as
    ``com.kaiten.deployment_zone.v1.deleted``.
    """

    name: Literal["DEPLOYMENT_ZONE_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.deployment_zone.v1.deleted"]
    """The event type: what tells one event from another."""

    data: DeploymentZone
    """What the event is about."""


class ReleaseDeployedEvent(KaitenModel):
    """Triggered when a release is deployed to a deployment zone, either at zone creation or
    when an existing zone's release changes. Delivered as
    ``com.kaiten.deployment_zone.v1.release_deployed``.
    """

    name: Literal["RELEASE_DEPLOYED"]
    """The event name."""

    type: Literal["com.kaiten.deployment_zone.v1.release_deployed"]
    """The event type: what tells one event from another."""

    data: Deployment
    """What the event is about."""


class DeploymentZoneUpdatedEvent(KaitenModel):
    """Triggered when a deployment zone is updated. Delivered as
    ``com.kaiten.deployment_zone.v1.updated``.
    """

    name: Literal["DEPLOYMENT_ZONE_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.deployment_zone.v1.updated"]
    """The event type: what tells one event from another."""

    data: DeploymentZone
    """What the event is about."""


class EntitlementCreatedEvent(KaitenModel):
    """Triggered when a new entitlement is created. Delivered as
    ``com.kaiten.entitlement.v1.created``.
    """

    name: Literal["ENTITLEMENT_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.entitlement.v1.created"]
    """The event type: what tells one event from another."""

    data: Entitlement
    """What the event is about."""


class EntitlementDeletedEvent(KaitenModel):
    """Triggered when an entitlement is deleted. Delivered as
    ``com.kaiten.entitlement.v1.deleted``.
    """

    name: Literal["ENTITLEMENT_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.entitlement.v1.deleted"]
    """The event type: what tells one event from another."""

    data: Entitlement
    """What the event is about."""


class EntitlementUpdatedEvent(KaitenModel):
    """Triggered when an entitlement is updated. Delivered as
    ``com.kaiten.entitlement.v1.updated``.
    """

    name: Literal["ENTITLEMENT_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.entitlement.v1.updated"]
    """The event type: what tells one event from another."""

    data: Entitlement
    """What the event is about."""


class EntitlementGroupCreatedEvent(KaitenModel):
    """Triggered when a new entitlement group is created. Delivered as
    ``com.kaiten.entitlement_group.v1.created``.
    """

    name: Literal["ENTITLEMENT_GROUP_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.entitlement_group.v1.created"]
    """The event type: what tells one event from another."""

    data: EntitlementGroup
    """What the event is about."""


class EntitlementGroupDeletedEvent(KaitenModel):
    """Triggered when an entitlement group is deleted. Delivered as
    ``com.kaiten.entitlement_group.v1.deleted``.
    """

    name: Literal["ENTITLEMENT_GROUP_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.entitlement_group.v1.deleted"]
    """The event type: what tells one event from another."""

    data: EntitlementGroup
    """What the event is about."""


class EntitlementGroupUpdatedEvent(KaitenModel):
    """Triggered when an entitlement group is updated. Delivered as
    ``com.kaiten.entitlement_group.v1.updated``.
    """

    name: Literal["ENTITLEMENT_GROUP_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.entitlement_group.v1.updated"]
    """The event type: what tells one event from another."""

    data: EntitlementGroup
    """What the event is about."""


class FeatureFlagCreatedEvent(KaitenModel):
    """Triggered when a new feature flag is created. Delivered as
    ``com.kaiten.feature_flag.v1.created``.
    """

    name: Literal["FEATURE_FLAG_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.feature_flag.v1.created"]
    """The event type: what tells one event from another."""

    data: FeatureFlag
    """What the event is about."""


class FeatureFlagDeletedEvent(KaitenModel):
    """Triggered when a feature flag is deleted. Delivered as
    ``com.kaiten.feature_flag.v1.deleted``.
    """

    name: Literal["FEATURE_FLAG_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.feature_flag.v1.deleted"]
    """The event type: what tells one event from another."""

    data: FeatureFlag
    """What the event is about."""


class FeatureFlagEvaluatedEvent(KaitenModel):
    """Triggered on every flag evaluation. The payload carries no evaluation context, so no
    targeting key or user attribute is exposed. Delivered as
    ``com.kaiten.feature_flag.v1.evaluated``.
    """

    name: Literal["FEATURE_FLAG_EVALUATED"]
    """The event name."""

    type: Literal["com.kaiten.feature_flag.v1.evaluated"]
    """The event type: what tells one event from another."""

    data: FeatureFlagEvaluated
    """What the event is about."""


class FeatureFlagUpdatedEvent(KaitenModel):
    """Triggered when a feature flag is updated. Delivered as
    ``com.kaiten.feature_flag.v1.updated``.
    """

    name: Literal["FEATURE_FLAG_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.feature_flag.v1.updated"]
    """The event type: what tells one event from another."""

    data: FeatureFlag
    """What the event is about."""


class SystemOrganizationTokenIssuedEvent(KaitenModel):
    """Triggered when a platform credential mints an organization-scoped credential for the
    `system:kaiten` platform identity inside this organization. Carries the platform
    credential that performed the mint and the scopes granted, never the credential value.
    Expect this at the rate an integration refreshes: roughly 120 per day per process at a
    15-minute lifetime. Delivered as ``com.kaiten.identity.v1.system_token_issued``.
    """

    name: Literal["SYSTEM_ORGANIZATION_TOKEN_ISSUED"]
    """The event name."""

    type: Literal["com.kaiten.identity.v1.system_token_issued"]
    """The event type: what tells one event from another."""

    data: SystemTokenIssuance
    """What the event is about."""


class InstanceEntitlementCapExceededEvent(KaitenModel):
    """Triggered when a SOFT-enforcement entitlement's usage crosses from below the cap to
    above it. Fires once per crossing. Delivered as
    ``com.kaiten.instance.entitlement.v1.cap_exceeded``.
    """

    name: Literal["INSTANCE_ENTITLEMENT_CAP_EXCEEDED"]
    """The event name."""

    type: Literal["com.kaiten.instance.entitlement.v1.cap_exceeded"]
    """The event type: what tells one event from another."""

    data: InstanceEntitlementCapExceeded
    """What the event is about."""


class InstanceEntitlementUsagePeriodRolledOverEvent(KaitenModel):
    """Triggered once per usage window closed by a report: the entitlement's own stored bucket,
    and one synthetic event per window skipped entirely since the last report. Delivered as
    ``com.kaiten.instance.entitlement.v1.usage_period_rolled_over``.
    """

    name: Literal["INSTANCE_ENTITLEMENT_USAGE_PERIOD_ROLLED_OVER"]
    """The event name."""

    type: Literal["com.kaiten.instance.entitlement.v1.usage_period_rolled_over"]
    """The event type: what tells one event from another."""

    data: InstanceEntitlementUsagePeriodRolledOver
    """What the event is about."""


class InstanceEntitlementUsageReachedEvent(KaitenModel):
    """Triggered when an instance's entitlement usage reaches its threshold. Delivered as
    ``com.kaiten.instance.entitlement.v1.usage_reached``.
    """

    name: Literal["INSTANCE_ENTITLEMENT_USAGE_REACHED"]
    """The event name."""

    type: Literal["com.kaiten.instance.entitlement.v1.usage_reached"]
    """The event type: what tells one event from another."""

    data: EntitlementUsage
    """What the event is about."""


class InstanceEntitlementUsageReportAcceptedEvent(KaitenModel):
    """Triggered when a usage report is persisted, including a SOFT-enforcement overage.
    Delivered as ``com.kaiten.instance.entitlement.v1.usage_report_accepted``.
    """

    name: Literal["ENTITLEMENT_USAGE_REPORT_ACCEPTED"]
    """The event name."""

    type: Literal["com.kaiten.instance.entitlement.v1.usage_report_accepted"]
    """The event type: what tells one event from another."""

    data: InstanceEntitlementUsageReportAccepted
    """What the event is about."""


class InstanceEntitlementUsageReportRejectedEvent(KaitenModel):
    """Triggered when a usage report is refused because it would take a HARD-enforcement
    entitlement past its cap. The usage is not persisted. Delivered as
    ``com.kaiten.instance.entitlement.v1.usage_report_rejected``.
    """

    name: Literal["ENTITLEMENT_USAGE_REPORT_REJECTED"]
    """The event name."""

    type: Literal["com.kaiten.instance.entitlement.v1.usage_report_rejected"]
    """The event type: what tells one event from another."""

    data: InstanceEntitlementUsageReportAccepted
    """What the event is about."""


class InstanceEntitlementUsageWarningThresholdReachedEvent(KaitenModel):
    """Triggered when an instance's entitlement usage crosses its configured early-warning
    percentage boundary, before the cap is reached. Fires once per crossing. Delivered as
    ``com.kaiten.instance.entitlement.v1.usage_warning_threshold_reached``.
    """

    name: Literal["INSTANCE_ENTITLEMENT_USAGE_WARNING_THRESHOLD_REACHED"]
    """The event name."""

    type: Literal["com.kaiten.instance.entitlement.v1.usage_warning_threshold_reached"]
    """The event type: what tells one event from another."""

    data: InstanceEntitlementUsageWarningThresholdReached
    """What the event is about."""


class InstanceEntitlementValueGetEvent(KaitenModel):
    """Triggered on every read of an instance entitlement's usage value. This is a read audit
    signal, not a state change. Delivered as
    ``com.kaiten.instance.entitlement.v1.value_get``.
    """

    name: Literal["ENTITLEMENT_VALUE_GET"]
    """The event name."""

    type: Literal["com.kaiten.instance.entitlement.v1.value_get"]
    """The event type: what tells one event from another."""

    data: InstanceEntitlementValueGet
    """What the event is about."""


class InstanceCreatedEvent(KaitenModel):
    """Triggered when a new instance is created. Delivered as ``com.kaiten.instance.v1.created``."""

    name: Literal["INSTANCE_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.instance.v1.created"]
    """The event type: what tells one event from another."""

    data: Instance
    """What the event is about."""


class InstanceDeletedEvent(KaitenModel):
    """Triggered when an instance is deleted. Delivered as ``com.kaiten.instance.v1.deleted``."""

    name: Literal["INSTANCE_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.instance.v1.deleted"]
    """The event type: what tells one event from another."""

    data: Instance
    """What the event is about."""


class InstanceDeployedEvent(KaitenModel):
    """Triggered when an instance is deployed to a deployment zone. Delivered as
    ``com.kaiten.instance.v1.deployed``.
    """

    name: Literal["INSTANCE_DEPLOYED"]
    """The event name."""

    type: Literal["com.kaiten.instance.v1.deployed"]
    """The event type: what tells one event from another."""

    data: Instance
    """What the event is about."""


class InstanceLifecycleStageChangedEvent(KaitenModel):
    """Triggered when an instance commercial lifecycle stage changes. Delivered as
    ``com.kaiten.instance.v1.lifecycle_stage_changed``.
    """

    name: Literal["INSTANCE_LIFECYCLE_STAGE_CHANGED"]
    """The event name."""

    type: Literal["com.kaiten.instance.v1.lifecycle_stage_changed"]
    """The event type: what tells one event from another."""

    data: InstanceLifecycleStageChanged
    """What the event is about."""


class InstanceMigratedEvent(KaitenModel):
    """Triggered when an instance is migrated from one deployment zone to another. Delivered as
    ``com.kaiten.instance.v1.migrated``.
    """

    name: Literal["INSTANCE_MIGRATED"]
    """The event name."""

    type: Literal["com.kaiten.instance.v1.migrated"]
    """The event type: what tells one event from another."""

    data: Instance
    """What the event is about."""


class InstanceStatusChangedEvent(KaitenModel):
    """Triggered when an instance operational status changes. Delivered as
    ``com.kaiten.instance.v1.status_changed``.
    """

    name: Literal["INSTANCE_STATUS_CHANGED"]
    """The event name."""

    type: Literal["com.kaiten.instance.v1.status_changed"]
    """The event type: what tells one event from another."""

    data: InstanceStatusChanged
    """What the event is about."""


class InstanceUpdatedEvent(KaitenModel):
    """Triggered when an instance is updated. Delivered as ``com.kaiten.instance.v1.updated``."""

    name: Literal["INSTANCE_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.instance.v1.updated"]
    """The event type: what tells one event from another."""

    data: Instance
    """What the event is about."""


class LicenseEntitlementAssignedEvent(KaitenModel):
    """Triggered when an entitlement is assigned to a license. Delivered as
    ``com.kaiten.license.entitlement.v1.assigned``.
    """

    name: Literal["LICENSE_ENTITLEMENT_ASSIGNED"]
    """The event name."""

    type: Literal["com.kaiten.license.entitlement.v1.assigned"]
    """The event type: what tells one event from another."""

    data: LicenseEntitlement
    """What the event is about."""


class LicenseEntitlementUnassignedEvent(KaitenModel):
    """Triggered when an entitlement is unassigned from a license. Delivered as
    ``com.kaiten.license.entitlement.v1.unassigned``.
    """

    name: Literal["LICENSE_ENTITLEMENT_UNASSIGNED"]
    """The event name."""

    type: Literal["com.kaiten.license.entitlement.v1.unassigned"]
    """The event type: what tells one event from another."""

    data: LicenseEntitlement
    """What the event is about."""


class LicenseEntitlementUpdatedEvent(KaitenModel):
    """Triggered when a license entitlement is updated. Delivered as
    ``com.kaiten.license.entitlement.v1.updated``.
    """

    name: Literal["LICENSE_ENTITLEMENT_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.license.entitlement.v1.updated"]
    """The event type: what tells one event from another."""

    data: LicenseEntitlement
    """What the event is about."""


class LicenseArchivedEvent(KaitenModel):
    """Triggered when a published license version is archived and withdrawn from sale.
    Delivered as ``com.kaiten.license.v1.archived``.
    """

    name: Literal["LICENSE_ARCHIVED"]
    """The event name."""

    type: Literal["com.kaiten.license.v1.archived"]
    """The event type: what tells one event from another."""

    data: License
    """What the event is about."""


class LicenseCreatedEvent(KaitenModel):
    """Triggered when a new license is created. Delivered as ``com.kaiten.license.v1.created``."""

    name: Literal["LICENSE_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.license.v1.created"]
    """The event type: what tells one event from another."""

    data: License
    """What the event is about."""


class LicenseDeletedEvent(KaitenModel):
    """Triggered when a license is deleted. Delivered as ``com.kaiten.license.v1.deleted``."""

    name: Literal["LICENSE_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.license.v1.deleted"]
    """The event type: what tells one event from another."""

    data: License
    """What the event is about."""


class LicensePublishedEvent(KaitenModel):
    """Triggered when a draft license version is published and goes on sale. Delivered as
    ``com.kaiten.license.v1.published``.
    """

    name: Literal["LICENSE_PUBLISHED"]
    """The event name."""

    type: Literal["com.kaiten.license.v1.published"]
    """The event type: what tells one event from another."""

    data: License
    """What the event is about."""


class LicenseUnarchivedEvent(KaitenModel):
    """Triggered when an archived license version is put back on sale. Delivered as
    ``com.kaiten.license.v1.unarchived``.
    """

    name: Literal["LICENSE_UNARCHIVED"]
    """The event name."""

    type: Literal["com.kaiten.license.v1.unarchived"]
    """The event type: what tells one event from another."""

    data: License
    """What the event is about."""


class LicenseUpdatedEvent(KaitenModel):
    """Triggered when a license is updated. Delivered as ``com.kaiten.license.v1.updated``."""

    name: Literal["LICENSE_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.license.v1.updated"]
    """The event type: what tells one event from another."""

    data: License
    """What the event is about."""


class LicenseFamilyCreatedEvent(KaitenModel):
    """Triggered when a license is created without naming a family: its version 1 opens a new
    family, which this event carries, with the version it serves -- none if that version is
    a draft. It is recorded in the same transaction as that version's LICENSE_CREATED.
    Delivered as ``com.kaiten.license_family.v1.created``.
    """

    name: Literal["LICENSE_FAMILY_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.license_family.v1.created"]
    """The event type: what tells one event from another."""

    data: LicenseFamilyView
    """What the event is about."""


class LicenseFamilyDeletedEvent(KaitenModel):
    """Triggered when a license family's last version is deleted, which deletes the family and
    frees its slug. It carries the family as it stood before that version went, and is
    recorded in the same transaction as that version's LICENSE_DELETED. Delivered as
    ``com.kaiten.license_family.v1.deleted``.
    """

    name: Literal["LICENSE_FAMILY_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.license_family.v1.deleted"]
    """The event type: what tells one event from another."""

    data: LicenseFamilyView
    """What the event is about."""


class LicenseFamilyUpdatedEvent(KaitenModel):
    """Triggered when a license family starts serving another version, or none: a newer version
    published, a version published, archived or unarchived, the family's default taken or
    given up, or the served version deleted. It carries the family with the version it
    serves now, and is recorded in the same transaction as the version event that caused the
    change. A change that leaves the served version where it was -- a draft added, a version
    renamed, a default restated -- triggers none. Delivered as
    ``com.kaiten.license_family.v1.updated``.
    """

    name: Literal["LICENSE_FAMILY_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.license_family.v1.updated"]
    """The event type: what tells one event from another."""

    data: LicenseFamilyView
    """What the event is about."""


class MetadataFieldArchivedEvent(KaitenModel):
    """Triggered when a metadata field is archived and leaves the active schema composition.
    Delivered as ``com.kaiten.metadata_field.v1.archived``.
    """

    name: Literal["METADATA_FIELD_ARCHIVED"]
    """The event name."""

    type: Literal["com.kaiten.metadata_field.v1.archived"]
    """The event type: what tells one event from another."""

    data: MetadataField
    """What the event is about."""


class MetadataFieldCreatedEvent(KaitenModel):
    """Triggered when a metadata field is declared for a resource type. Delivered as
    ``com.kaiten.metadata_field.v1.created``.
    """

    name: Literal["METADATA_FIELD_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.metadata_field.v1.created"]
    """The event type: what tells one event from another."""

    data: MetadataField
    """What the event is about."""


class MetadataFieldReorderedEvent(KaitenModel):
    """Triggered when the display order of a resource type's metadata fields is rewritten.
    Delivered as ``com.kaiten.metadata_field.v1.reordered``.
    """

    name: Literal["METADATA_FIELD_REORDERED"]
    """The event name."""

    type: Literal["com.kaiten.metadata_field.v1.reordered"]
    """The event type: what tells one event from another."""

    data: MetadataFieldReordered
    """What the event is about."""


class MetadataFieldUnarchivedEvent(KaitenModel):
    """Triggered when an archived metadata field is restored to the active schema composition.
    Delivered as ``com.kaiten.metadata_field.v1.unarchived``.
    """

    name: Literal["METADATA_FIELD_UNARCHIVED"]
    """The event name."""

    type: Literal["com.kaiten.metadata_field.v1.unarchived"]
    """The event type: what tells one event from another."""

    data: MetadataField
    """What the event is about."""


class MetadataFieldUpdatedEvent(KaitenModel):
    """Triggered when a metadata field's label or JSON schema changes. A reordering emits
    METADATA_FIELD_REORDERED instead. Delivered as ``com.kaiten.metadata_field.v1.updated``.
    """

    name: Literal["METADATA_FIELD_UPDATED"]
    """The event name."""

    type: Literal["com.kaiten.metadata_field.v1.updated"]
    """The event type: what tells one event from another."""

    data: MetadataField
    """What the event is about."""


class ReleaseCreatedEvent(KaitenModel):
    """Triggered when a new release is created. Delivered as ``com.kaiten.release.v1.created``."""

    name: Literal["RELEASE_CREATED"]
    """The event name."""

    type: Literal["com.kaiten.release.v1.created"]
    """The event type: what tells one event from another."""

    data: Release
    """What the event is about."""


class ReleaseDeletedEvent(KaitenModel):
    """Triggered when a release is deleted. Delivered as ``com.kaiten.release.v1.deleted``."""

    name: Literal["RELEASE_DELETED"]
    """The event name."""

    type: Literal["com.kaiten.release.v1.deleted"]
    """The event type: what tells one event from another."""

    data: Release
    """What the event is about."""


WebhookEvent = Annotated[
    ComponentCreatedEvent
    | ComponentDeletedEvent
    | ComponentUpdatedEvent
    | CustomerCreatedEvent
    | CustomerCreationRejectedEvent
    | CustomerDeletedEvent
    | CustomerUpdatedEvent
    | DeploymentZoneCreatedEvent
    | DeploymentZoneDeletedEvent
    | ReleaseDeployedEvent
    | DeploymentZoneUpdatedEvent
    | EntitlementCreatedEvent
    | EntitlementDeletedEvent
    | EntitlementUpdatedEvent
    | EntitlementGroupCreatedEvent
    | EntitlementGroupDeletedEvent
    | EntitlementGroupUpdatedEvent
    | FeatureFlagCreatedEvent
    | FeatureFlagDeletedEvent
    | FeatureFlagEvaluatedEvent
    | FeatureFlagUpdatedEvent
    | SystemOrganizationTokenIssuedEvent
    | InstanceEntitlementCapExceededEvent
    | InstanceEntitlementUsagePeriodRolledOverEvent
    | InstanceEntitlementUsageReachedEvent
    | InstanceEntitlementUsageReportAcceptedEvent
    | InstanceEntitlementUsageReportRejectedEvent
    | InstanceEntitlementUsageWarningThresholdReachedEvent
    | InstanceEntitlementValueGetEvent
    | InstanceCreatedEvent
    | InstanceDeletedEvent
    | InstanceDeployedEvent
    | InstanceLifecycleStageChangedEvent
    | InstanceMigratedEvent
    | InstanceStatusChangedEvent
    | InstanceUpdatedEvent
    | LicenseEntitlementAssignedEvent
    | LicenseEntitlementUnassignedEvent
    | LicenseEntitlementUpdatedEvent
    | LicenseArchivedEvent
    | LicenseCreatedEvent
    | LicenseDeletedEvent
    | LicensePublishedEvent
    | LicenseUnarchivedEvent
    | LicenseUpdatedEvent
    | LicenseFamilyCreatedEvent
    | LicenseFamilyDeletedEvent
    | LicenseFamilyUpdatedEvent
    | MetadataFieldArchivedEvent
    | MetadataFieldCreatedEvent
    | MetadataFieldReorderedEvent
    | MetadataFieldUnarchivedEvent
    | MetadataFieldUpdatedEvent
    | ReleaseCreatedEvent
    | ReleaseDeletedEvent,
    Field(discriminator="type"),
]
"""Any event Kaiten delivers to a webhook endpoint, discriminated by ``type``."""

WEBHOOK_EVENTS: dict[str, type[KaitenModel]] = {
    "com.kaiten.component.v1.created": ComponentCreatedEvent,
    "com.kaiten.component.v1.deleted": ComponentDeletedEvent,
    "com.kaiten.component.v1.updated": ComponentUpdatedEvent,
    "com.kaiten.customer.v1.created": CustomerCreatedEvent,
    "com.kaiten.customer.v1.creation_rejected": CustomerCreationRejectedEvent,
    "com.kaiten.customer.v1.deleted": CustomerDeletedEvent,
    "com.kaiten.customer.v1.updated": CustomerUpdatedEvent,
    "com.kaiten.deployment_zone.v1.created": DeploymentZoneCreatedEvent,
    "com.kaiten.deployment_zone.v1.deleted": DeploymentZoneDeletedEvent,
    "com.kaiten.deployment_zone.v1.release_deployed": ReleaseDeployedEvent,
    "com.kaiten.deployment_zone.v1.updated": DeploymentZoneUpdatedEvent,
    "com.kaiten.entitlement.v1.created": EntitlementCreatedEvent,
    "com.kaiten.entitlement.v1.deleted": EntitlementDeletedEvent,
    "com.kaiten.entitlement.v1.updated": EntitlementUpdatedEvent,
    "com.kaiten.entitlement_group.v1.created": EntitlementGroupCreatedEvent,
    "com.kaiten.entitlement_group.v1.deleted": EntitlementGroupDeletedEvent,
    "com.kaiten.entitlement_group.v1.updated": EntitlementGroupUpdatedEvent,
    "com.kaiten.feature_flag.v1.created": FeatureFlagCreatedEvent,
    "com.kaiten.feature_flag.v1.deleted": FeatureFlagDeletedEvent,
    "com.kaiten.feature_flag.v1.evaluated": FeatureFlagEvaluatedEvent,
    "com.kaiten.feature_flag.v1.updated": FeatureFlagUpdatedEvent,
    "com.kaiten.identity.v1.system_token_issued": SystemOrganizationTokenIssuedEvent,
    "com.kaiten.instance.entitlement.v1.cap_exceeded": InstanceEntitlementCapExceededEvent,
    "com.kaiten.instance.entitlement.v1.usage_period_rolled_over": InstanceEntitlementUsagePeriodRolledOverEvent,
    "com.kaiten.instance.entitlement.v1.usage_reached": InstanceEntitlementUsageReachedEvent,
    "com.kaiten.instance.entitlement.v1.usage_report_accepted": InstanceEntitlementUsageReportAcceptedEvent,
    "com.kaiten.instance.entitlement.v1.usage_report_rejected": InstanceEntitlementUsageReportRejectedEvent,
    "com.kaiten.instance.entitlement.v1.usage_warning_threshold_reached": InstanceEntitlementUsageWarningThresholdReachedEvent,
    "com.kaiten.instance.entitlement.v1.value_get": InstanceEntitlementValueGetEvent,
    "com.kaiten.instance.v1.created": InstanceCreatedEvent,
    "com.kaiten.instance.v1.deleted": InstanceDeletedEvent,
    "com.kaiten.instance.v1.deployed": InstanceDeployedEvent,
    "com.kaiten.instance.v1.lifecycle_stage_changed": InstanceLifecycleStageChangedEvent,
    "com.kaiten.instance.v1.migrated": InstanceMigratedEvent,
    "com.kaiten.instance.v1.status_changed": InstanceStatusChangedEvent,
    "com.kaiten.instance.v1.updated": InstanceUpdatedEvent,
    "com.kaiten.license.entitlement.v1.assigned": LicenseEntitlementAssignedEvent,
    "com.kaiten.license.entitlement.v1.unassigned": LicenseEntitlementUnassignedEvent,
    "com.kaiten.license.entitlement.v1.updated": LicenseEntitlementUpdatedEvent,
    "com.kaiten.license.v1.archived": LicenseArchivedEvent,
    "com.kaiten.license.v1.created": LicenseCreatedEvent,
    "com.kaiten.license.v1.deleted": LicenseDeletedEvent,
    "com.kaiten.license.v1.published": LicensePublishedEvent,
    "com.kaiten.license.v1.unarchived": LicenseUnarchivedEvent,
    "com.kaiten.license.v1.updated": LicenseUpdatedEvent,
    "com.kaiten.license_family.v1.created": LicenseFamilyCreatedEvent,
    "com.kaiten.license_family.v1.deleted": LicenseFamilyDeletedEvent,
    "com.kaiten.license_family.v1.updated": LicenseFamilyUpdatedEvent,
    "com.kaiten.metadata_field.v1.archived": MetadataFieldArchivedEvent,
    "com.kaiten.metadata_field.v1.created": MetadataFieldCreatedEvent,
    "com.kaiten.metadata_field.v1.reordered": MetadataFieldReorderedEvent,
    "com.kaiten.metadata_field.v1.unarchived": MetadataFieldUnarchivedEvent,
    "com.kaiten.metadata_field.v1.updated": MetadataFieldUpdatedEvent,
    "com.kaiten.release.v1.created": ReleaseCreatedEvent,
    "com.kaiten.release.v1.deleted": ReleaseDeletedEvent,
}
"""Every published event type, mapped to the model that parses it."""
