# Copyright 2026 KAITEN INC
# SPDX-License-Identifier: Apache-2.0

# Generated by scripts/unasync.py from src/kaitencloud/_async/resources/_base.py. Do not edit by hand:
# change the async source, then run `task generate`.
from __future__ import annotations

from .._http import APIClient

__all__ = ["Resource"]


class Resource:
    """Base class of a resource namespace, such as ``client.customers``."""

    __slots__ = ("_api",)

    def __init__(self, api: APIClient) -> None:
        self._api = api

    def __repr__(self) -> str:
        return f"<{type(self).__name__} base_url={self._api.base_url!r}>"
