# Copyright 2026 KAITEN INC
# SPDX-License-Identifier: Apache-2.0

# Generated by scripts/unasync.py from src/kaitencloud/_async/resources/instances.py. Do not edit by hand:
# change the async source, then run `task generate`.
from __future__ import annotations

import builtins
from collections.abc import Mapping
from datetime import datetime
from typing import Any

from ..._exceptions import ThresholdExceededError
from ..._utils import (
    api_path,
    compact,
    format_datetime,
    integration_body,
    integrations_body,
    optional_datetime,
)
from ...types import (
    AuditTrail,
    EntitlementUsage,
    Instance,
    InstanceIntegration,
    InstanceStatus,
    IntegrationParam,
    UsageBehavior,
)
from ._base import Resource

__all__ = ["Instances"]


class Instances(Resource):
    """Instances: deployments of your product for a customer, under a license.

    An instance is where entitlements meet reality: usage is reported against it, and its
    audit trail records what happened to it.
    """

    def list(self) -> builtins.list[Instance]:
        """Return every instance, walking all pages."""
        return self._api.list_all("/instances", Instance)

    def get(self, instance_slug: str) -> Instance:
        """Return the instance identified by ``instance_slug``."""
        return self._api.get(api_path("instances", instance_slug), Instance)

    def create(
        self,
        *,
        name: str,
        customer_id: str,
        license_id: str,
        start_license_date: datetime | str,
        end_license_date: datetime | str,
        description: str = "",
        deployment_zone_id: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        slug: str | None = None,
        integrations: Mapping[str, IntegrationParam] | None = None,
    ) -> Instance:
        """Create an instance.

        Args:
            name: The instance's name.
            customer_id: The id -- not the slug -- of the customer it is deployed for.
            license_id: The id of the license it runs under.
            start_license_date: When its license term starts: a timezone-aware datetime, or an
                RFC 3339 string.
            end_license_date: When its license term ends.
            description: A description.
            deployment_zone_id: The id of the deployment zone it runs in.
            metadata: Typed metadata, validated against the organization's ``INSTANCE``
                metadata fields.
            slug: Its URL-friendly identifier, generated when omitted.
            integrations: Links to records in third-party systems, keyed by adapter name.
                Only settable here: afterwards, use :meth:`update_integration`.

        Raises:
            NotFoundError: The customer, license or deployment zone does not exist in this
                organization.
            ConflictError: The slug is taken, or the organization reached its instance limit.
        """
        body = {
            **_instance(
                name=name,
                customer_id=customer_id,
                license_id=license_id,
                start_license_date=start_license_date,
                end_license_date=end_license_date,
                description=description,
                deployment_zone_id=deployment_zone_id,
                metadata=metadata,
            ),
            **compact({"slug": slug, "integrations": integrations_body(integrations)}),
        }
        return self._api.send("POST", "/instances", Instance, body=body)

    def update(
        self,
        instance_slug: str,
        *,
        name: str,
        customer_id: str,
        license_id: str,
        start_license_date: datetime | str,
        end_license_date: datetime | str,
        description: str = "",
        deployment_zone_id: str | None = None,
        metadata: Mapping[str, Any] | None = None,
        slug: str | None = None,
    ) -> None:
        """Replace an instance's details.

        A full replacement, with two fields where leaving a value out keeps the current one:
        ``deployment_zone_id`` and ``slug``. Passing a ``slug`` renames the instance.
        ``metadata`` replaces the whole blob, so send back the keys to keep.

        Moving an instance into a deployment zone, or to another one, is how a deployment or a
        migration is recorded: there is no separate call for either.
        """
        body = {
            **_instance(
                name=name,
                customer_id=customer_id,
                license_id=license_id,
                start_license_date=start_license_date,
                end_license_date=end_license_date,
                description=description,
                deployment_zone_id=deployment_zone_id,
                metadata=metadata,
            ),
            **compact({"slug": slug}),
        }
        self._api.send_empty("PUT", api_path("instances", instance_slug), body=body)

    def update_status(self, instance_slug: str, status: InstanceStatus) -> None:
        """Set an instance's operational status, leaving everything else untouched.

        ``status`` is ``HEALTHY``, ``DEGRADED``, ``INCIDENT`` or ``MAINTENANCE``.
        """
        self._api.send_empty(
            "PATCH", api_path("instances", instance_slug), body={"status": status}, idempotent=True
        )

    def update_lifecycle_stage(self, instance_slug: str, lifecycle_stage: str) -> None:
        """Set an instance's commercial lifecycle stage, leaving everything else untouched.

        Free-form; ``TRIAL``, ``ACTIVE``, ``AT_RISK`` and ``CHURNED`` are the suggested stages.
        """
        self._api.send_empty(
            "PATCH",
            api_path("instances", instance_slug),
            body={"lifecycleStage": lifecycle_stage},
            idempotent=True,
        )

    def delete(self, instance_slug: str) -> None:
        """Delete the instance identified by ``instance_slug``. The deletion is permanent."""
        self._api.send_empty("DELETE", api_path("instances", instance_slug))

    def list_audit_trails(
        self,
        instance_slug: str,
        *,
        event_name: str | None = None,
        after: datetime | str | None = None,
        before: datetime | str | None = None,
        limit: int | None = None,
    ) -> builtins.list[AuditTrail]:
        """Return an instance's audit trail entries.

        The audit trail grows without bound, so ``limit`` is a ceiling rather than a page
        size: pages are walked until that many entries are held, and no page asks for more
        than are still wanted. Without a limit, every entry is returned.

        Args:
            instance_slug: The instance whose audit trail to read.
            event_name: Only entries of this event, e.g. ``"INSTANCE_STATUS_CHANGED"``.
            after: Only entries at or after this moment.
            before: Only entries at or before this moment.
            limit: The most entries to return.
        """
        if limit is not None and limit < 1:
            raise ValueError(f"limit must be at least 1, got {limit}")
        return self._api.list_all(
            api_path("instances", instance_slug, "audit-trails"),
            AuditTrail,
            params={
                "event_name": event_name,
                "after": optional_datetime(after),
                "before": optional_datetime(before),
            },
            limit=limit,
        )

    def list_usage(self, instance_slug: str) -> builtins.list[EntitlementUsage]:
        """Return the instance's usage of every entitlement, each next to the grant it counts against."""
        return self._api.get_list(
            api_path("instances", instance_slug, "entitlements", "usage"), EntitlementUsage
        )

    def get_usage(self, instance_slug: str, entitlement_slug: str) -> EntitlementUsage:
        """Return the instance's usage of one entitlement, next to the grant it counts against.

        For a periodic entitlement, ``current_period_start`` and ``current_period_end`` bound
        the window the usage belongs to; both are ``None`` for a lifetime counter. Each read is
        recorded as an ``ENTITLEMENT_VALUE_GET`` event.
        """
        return self._api.get(
            api_path("instances", instance_slug, "entitlements", entitlement_slug, "usage"),
            EntitlementUsage,
        )

    def report_usage(
        self,
        instance_slug: str,
        entitlement_slug: str,
        value: float,
        *,
        behavior: UsageBehavior = "append",
        metadata: Mapping[str, Any] | None = None,
    ) -> EntitlementUsage:
        """Report usage of a NUMBER entitlement, and return the usage it results in.

        Args:
            instance_slug: The instance that consumed.
            entitlement_slug: The entitlement consumed.
            value: The amount. With ``behavior="append"`` it is folded into the stored total
                through the entitlement's aggregation method (a sum, by default). With
                ``"set"`` it replaces the total -- which is also how to correct it downwards.
            behavior: ``"append"`` (the default) or ``"set"``.
            metadata: Free-form metadata recorded with the report.

        Raises:
            ThresholdExceededError: The report would take usage past the maximum the license
                allows -- the granted value plus its overage allowance. Nothing was recorded.

        Never retried automatically: without an idempotency key on the wire, a report retried
        after a lost response would be counted twice.
        """
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise TypeError(f"usage must be a number, got {type(value).__name__}")
        body = compact(
            {
                "value": {"type": "number", "value": value},
                "behavior": behavior,
                "metadata": dict(metadata) if metadata is not None else None,
            }
        )
        return self._api.send(
            "POST",
            api_path("instances", instance_slug, "entitlements", entitlement_slug, "usage"),
            EntitlementUsage,
            body=body,
            errors={409: ThresholdExceededError},
        )

    def get_integration(self, instance_slug: str, integration_name: str) -> InstanceIntegration:
        """Return the instance's link to the ``integration_name`` adapter."""
        return self._api.get(
            api_path("instances", instance_slug, "integrations", integration_name),
            InstanceIntegration,
        )

    def create_integration(
        self,
        instance_slug: str,
        integration_name: str,
        *,
        external_id: str,
        metadata: Mapping[str, Any] | None = None,
        web_url: str | None = None,
        last_error: str | None = None,
    ) -> InstanceIntegration:
        """Link the instance to a record in the ``integration_name`` adapter.

        Args:
            instance_slug: The instance to link.
            integration_name: The adapter, e.g. ``"attio"``.
            external_id: The record's identifier in the third-party system.
            metadata: Adapter-specific metadata.
            web_url: An absolute http(s) link to the record.
            last_error: The last synchronization error, if any.
        """
        return self._api.send(
            "POST",
            api_path("instances", instance_slug, "integrations", integration_name),
            InstanceIntegration,
            body=integration_body(
                external_id=external_id, metadata=metadata, web_url=web_url, last_error=last_error
            ),
        )

    def update_integration(
        self,
        instance_slug: str,
        integration_name: str,
        *,
        external_id: str,
        metadata: Mapping[str, Any] | None = None,
        web_url: str | None = None,
        last_error: str | None = None,
    ) -> InstanceIntegration:
        """Replace the instance's link to the ``integration_name`` adapter, and return it."""
        return self._api.send(
            "PUT",
            api_path("instances", instance_slug, "integrations", integration_name),
            InstanceIntegration,
            body=integration_body(
                external_id=external_id, metadata=metadata, web_url=web_url, last_error=last_error
            ),
        )

    def delete_integration(self, instance_slug: str, integration_name: str) -> None:
        """Remove the instance's link to the ``integration_name`` adapter."""
        self._api.send_empty(
            "DELETE", api_path("instances", instance_slug, "integrations", integration_name)
        )


def _instance(
    *,
    name: str,
    customer_id: str,
    license_id: str,
    start_license_date: datetime | str,
    end_license_date: datetime | str,
    description: str,
    deployment_zone_id: str | None,
    metadata: Mapping[str, Any] | None,
) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "customerId": customer_id,
        "licenseId": license_id,
        "startLicenseDate": format_datetime(start_license_date),
        "endLicenseDate": format_datetime(end_license_date),
        **compact(
            {
                "deploymentZoneId": deployment_zone_id,
                "metadata": dict(metadata) if metadata is not None else None,
            }
        ),
    }
