#!/usr/bin/env python3
# Copyright 2026 KAITEN INC
# SPDX-License-Identifier: Apache-2.0

"""Generate kaitencloud's pydantic models from the committed OpenAPI snapshots.

The SDK's models are never written by hand. They are rendered from ``openapi/openapi.yaml``
and ``openapi/platform-openapi.yaml`` -- the contract -- so a model can only drift from the
API by the snapshot drifting, which ``task sync:openapi`` fixes and CI catches.

Usage::

    uv run python scripts/generate_models.py          # rewrite src/kaitencloud/types/
    uv run python scripts/generate_models.py --check  # exit 1 when the committed files are stale

Three rules shape the output, each because the alternative breaks a caller:

- Only what the SDK can return is generated: the response schemas of the operations
  ``openapi/coverage.yaml`` maps, and the payloads of the published webhooks. Request bodies
  are built by the resource methods, and page envelopes are walked, never returned.
- Models are lenient where the contract grows. An enum with several values is typed
  ``Known | str``, so a value added to the API after a release parses instead of failing
  every read that carries it. Single-value enums stay exact: they are union tags.
- Nothing is guessed. A new multi-value enum or inline union must be named below, and an
  attribute that would shadow a pydantic member must be renamed below; the generator stops
  until it is.
"""

from __future__ import annotations

import argparse
import ast
import json
import keyword
import re
import sys
import textwrap
from collections.abc import Iterable, Iterator
from pathlib import Path
from typing import Any

import yaml
from _codegen import LICENSE_HEADER, ROOT, emit
from pydantic import BaseModel

CORE_SPEC = ROOT / "openapi" / "openapi.yaml"
PLATFORM_SPEC = ROOT / "openapi" / "platform-openapi.yaml"
COVERAGE = ROOT / "openapi" / "coverage.yaml"
TYPES = ROOT / "src" / "kaitencloud" / "types"
PARAMS = TYPES / "_params.py"

HTTP_METHODS = ("get", "put", "post", "patch", "delete")
PROSE = frozenset({"description", "examples", "example", "title"})
PAGE = re.compile(r"^Page[A-Z]")

HEADER = (
    LICENSE_HEADER
    + """
# Generated by scripts/generate_models.py from {source}. Do not edit by hand:
# change the contract (`task sync:openapi`) or the generator, then run `task generate`.
"""
)

# Public names for schemas whose contract name is too generic to export on its own.
CLASS_NAMES: dict[str, str] = {
    "Basic": "BasicVariant",
    "Impact": "MetadataFieldImpact",
    "ImpactSample": "MetadataFieldImpactSample",
    "RolloutDate": "RolloutDateVariant",
    "RolloutPercentage": "RolloutPercentageVariant",
}

# Names for inline unions, keyed by their members.
UNION_NAMES: dict[frozenset[str], str] = {
    frozenset(
        {"NumberEntitlementValue", "BooleanEntitlementValue", "ConfigEntitlementValue"}
    ): "EntitlementValue",
    frozenset(
        {"BasicTargeting", "RolloutDateTargeting", "RolloutPercentageTargeting"}
    ): "Targeting",
}

# Names for enums with more than one value, keyed by (schema, property).
ENUM_NAMES: dict[tuple[str, str], str] = {
    ("Entitlement", "aggregationMethod"): "AggregationMethod",
    ("Entitlement", "resetAnchor"): "ResetAnchor",
    ("Entitlement", "resetPeriod"): "ResetPeriod",
    ("Entitlement", "type"): "EntitlementType",
    ("FeatureFlag", "type"): "FeatureFlagType",
    ("Instance", "status"): "InstanceStatus",
    ("InstanceEntitlementUsageReportAccepted", "behavior"): "UsageBehavior",
    ("InstanceEntitlementUsageReportAccepted", "status"): "UsageReportStatus",
    ("InstanceStatusChanged", "new_status"): "InstanceStatus",
    ("InstanceStatusChanged", "previous_status"): "InstanceStatus",
    ("License", "lifecycleState"): "LicenseLifecycleState",
    ("License", "type"): "LicenseType",
    ("LicenseEntitlement", "entitlementType"): "LicenseEntitlementType",
    ("MetadataField", "resourceType"): "MetadataResourceType",
}

# Attribute names that would shadow a pydantic.BaseModel member, keyed by (schema, property).
FIELD_NAMES: dict[tuple[str, str], str] = {
    ("ConnectorSettingsSchema", "schema"): "json_schema",
}

ALIAS_DOCS: dict[str, str] = {
    "AggregationMethod": "How each reported usage value folds into an entitlement's stored total.",
    "DefaultVariant": "What a feature flag serves when no targeting rule matches, discriminated by ``type``.",
    "EntitlementType": "The value type of an entitlement in the catalog.",
    "EntitlementValue": "A typed entitlement value, discriminated by ``type``: a number, a boolean or a config object.",
    "FeatureFlagType": "The value type of a feature flag's variants.",
    "InstanceStatus": "The operational status of an instance.",
    "LicenseEntitlementType": "The value type of an entitlement granted by a license.",
    "LicenseLifecycleState": (
        "Whether a license version may be served: ``DRAFT`` before it goes on sale, "
        "``PUBLISHED`` while it is on sale, ``ARCHIVED`` once it has been withdrawn."
    ),
    "LicenseType": "The kind of a license.",
    "MetadataResourceType": "The resource a metadata field applies to.",
    "ResetAnchor": "What a periodic usage window is aligned on.",
    "ResetPeriod": "How often a periodic entitlement's usage resets.",
    "Scope": (
        "A permission an organization credential can carry, ``read:<resource>`` or "
        "``write:<resource>``; ``write`` implies ``read`` on the same resource."
    ),
    "Targeting": "One targeting rule of a feature flag, discriminated by ``type``.",
    "Targetings": "A feature flag's targeting rules, evaluated in order; the first match wins.",
    "UsageBehavior": "How a usage report applies: ``append`` folds the value in, ``set`` overwrites it.",
    "UsageReportStatus": "Whether a usage report was persisted.",
}

# Docstrings for the schemas the contract leaves undescribed.
CLASS_DOCS: dict[str, str] = {
    "AuditTrail": "One entry of an instance's audit trail.",
    "BasicTargeting": "A targeting rule that serves one variant to every context its CEL rule matches.",
    "BasicVariant": "A default variant that always serves one named variant.",
    "BooleanEntitlementValue": "A boolean entitlement value: whether a feature is included.",
    "Component": "A versioned building block of your product, that releases are made of.",
    "ConfigEntitlementValue": "A configuration entitlement value: a free-form object.",
    "Connector": "A connector registered with this Kaiten deployment.",
    "ConnectorActivation": "An organization's activation of a connector.",
    "ConnectorSettings": "An organization's settings for a connector.",
    "ConnectorSettingsSchema": "The JSON schema a connector's settings are validated against.",
    "ConnectorState": "Whether a connector is available, licensed and activated for this organization.",
    "Customer": "A customer of your organization: the end client instances are deployed for.",
    "CustomerCreationRejected": "A customer creation refused because the organization reached its limit.",
    "CustomerIntegration": "A customer's link to a record in a third-party system.",
    "CustomerIntegrationResource": "A customer as seen through one of its integrations.",
    "Deployment": "A release deployed to a deployment zone: an append-only history record.",
    "DeploymentZone": "An environment instances run in, and the release currently deployed to it.",
    "Entitlement": "A catalog entry: something a license can grant, and how its usage is measured.",
    "EntitlementGroup": "A named group of entitlements.",
    "EntitlementGroupSummary": "A reference to an entitlement group.",
    "EntitlementGroupUsage": "One entitlement's grant and usage within a group, for one instance.",
    "EntitlementUsage": "An instance's consumption of one entitlement, next to the grant it is measured against.",
    "ErrorDetail": "One validation problem inside an API error.",
    "FeatureFlag": "A feature flag: its variants, targeting rules and default variant.",
    "FeatureFlagEvaluated": "A feature flag evaluation, as reported to webhooks.",
    "Instance": "A deployment of your product for one customer, under one license.",
    "InstanceEntitlementCapExceeded": "Usage crossed an entitlement's included value, within its allowance.",
    "InstanceEntitlementUsagePeriodRolledOver": "A periodic usage window closed and a new one opened.",
    "InstanceEntitlementUsageReportAccepted": "The outcome of a usage report.",
    "InstanceEntitlementUsageWarningThresholdReached": "Usage crossed an entitlement's warning threshold.",
    "InstanceEntitlementValueGet": "An entitlement value read for an instance.",
    "InstanceIntegration": "An instance's link to a record in a third-party system.",
    "InstanceIntegrationResource": "An instance as seen through one of its integrations.",
    "InstanceLifecycleStageChanged": "An instance's commercial lifecycle stage changed.",
    "InstanceStatusChanged": "An instance's operational status changed.",
    "License": "A version of a license family: one set of entitlement grants, with its lifecycle state.",
    "LicenseFamilyView": "A license family -- the product -- resolved to one of its versions.",
    "LicenseEntitlement": "A grant: the value a license gives one entitlement, and how it is enforced.",
    "ManifestFlag": "One flag of the OpenFeature manifest.",
    "MetadataField": "A typed field an organization declares on its instances or deployment zones.",
    "MetadataFieldImpact": "What a candidate metadata field schema would invalidate.",
    "MetadataFieldImpactSample": "A resource a metadata field schema change would invalidate.",
    "MetadataFieldReordered": "Metadata fields were given a new display order.",
    "NumberEntitlementValue": "A numeric entitlement value: a quota, or an amount consumed.",
    "Organization": "A Kaiten organization: a tenant.",
    "PlainToken": "A token together with its plaintext secret, which the API returns exactly once.",
    "PlatformCredential": "The platform credential (``ksm_...``) a platform client authenticates with.",
    "Problem": "An RFC 9457 problem document, which every API error carries.",
    "Release": "An immutable, versioned set of components.",
    "RolloutDateTargeting": "A targeting rule that shifts traffic between variants over a date range.",
    "RolloutDateVariant": "A default variant that shifts traffic between variants over a date range.",
    "RolloutPercentageTargeting": "A targeting rule that splits the contexts it matches between variants.",
    "RolloutPercentageVariant": "A default variant that splits traffic between variants by weight.",
    "RolloutStep": "One end of a date-based rollout.",
    "ServiceAccount": "A machine identity inside an organization, owning API tokens.",
    "SystemTokenIssuance": "A platform credential minted a token inside this organization.",
    "Token": "A token's metadata. Never its secret.",
    "User": "A reference to the user behind an action.",
    "Variant": "One possible value of a feature flag.",
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate kaitencloud's models from the contract.")
    parser.add_argument(
        "--check", action="store_true", help="fail when the committed models are stale"
    )
    args = parser.parse_args()

    coverage = load(COVERAGE)
    core = load(CORE_SPEC)
    platform = load(PLATFORM_SPEC)

    core_source, core_names, core_exports = core_module(
        core, excluded=set(coverage["core"]["excluded"] or {})
    )
    platform_source, platform_exports = platform_module(
        platform, core, core_names, excluded=set(coverage["platform"]["excluded"] or {})
    )
    files = {
        TYPES / "__init__.py": types_package(core_exports, platform_exports),
        TYPES / "_core.py": core_source,
        TYPES / "_platform.py": platform_source,
        TYPES / "_webhooks.py": webhooks_module(core, core_names),
    }

    if emit(files, check=args.check):
        return 0
    if args.check:
        print("the generated models are stale: run `task generate`", file=sys.stderr)
        return 1
    return 0


def core_module(
    spec: dict[str, Any], *, excluded: set[str]
) -> tuple[str, dict[str, str], list[str]]:
    schemas = spec["components"]["schemas"]
    roots = response_roots(spec, excluded) | refs_in(spec.get("webhooks") or {})
    emitted = sorted(name for name in closure(schemas, roots) if not PAGE.match(name))
    names = {name: CLASS_NAMES.get(name, name) for name in emitted}

    module = ModelModule(source="openapi/openapi.yaml", schemas=schemas, names=names)
    for name in sorted(emitted, key=names.__getitem__):
        module.add_schema(name)
    module.enums["Scope"] = scopes(spec)
    return module.render(), names, module.exports


def scopes(spec: dict[str, Any]) -> tuple[str, ...]:
    """Every scope an organization credential can carry, as the contract publishes them."""
    published = {
        scope
        for scheme in (spec.get("components", {}).get("securitySchemes") or {}).values()
        for scope in scheme.get("x-kaiten-scopes") or ()
    }
    if not published:
        raise SystemExit("the contract publishes no x-kaiten-scopes: Scope would be empty")
    return tuple(sorted(published))


def platform_module(
    spec: dict[str, Any],
    core: dict[str, Any],
    core_names: dict[str, str],
    *,
    excluded: set[str],
) -> tuple[str, list[str]]:
    schemas = spec["components"]["schemas"]
    core_schemas = core["components"]["schemas"]

    names: dict[str, str] = {}
    own: list[str] = []
    for name in sorted(closure(schemas, response_roots(spec, excluded))):
        if name in core_names and without_prose(schemas[name]) == without_prose(core_schemas[name]):
            # The same shape under the same name: one Python class serves both surfaces.
            names[name] = core_names[name]
            continue
        python = CLASS_NAMES.get(name, name)
        if python in core_names.values():
            python = f"Platform{python}"
        names[name] = python
        own.append(name)

    module = ModelModule(source="openapi/platform-openapi.yaml", schemas=schemas, names=names)
    module.imports = {python for name, python in names.items() if name not in own}
    for name in own:
        module.add_schema(name)
    return module.render(), module.exports


def types_package(core_exports: list[str], platform_exports: list[str]) -> str:
    """``kaitencloud.types``: every generated model, and the hand-written ``*Param`` shapes."""
    groups = (
        ("_core", core_exports),
        ("_params", params_exports()),
        ("_platform", platform_exports),
    )
    lines = [
        HEADER.format(source="the snapshots in openapi/"),
        '"""Models and parameter types for the Kaiten API.',
        "",
        "The models are generated from the API contract. The ``*Param`` typed dictionaries describe",
        "the nested values the client methods accept.",
        '"""',
        "",
    ]
    for module, names in groups:
        lines += [f"from .{module} import (", *(f"    {name}," for name in names), ")"]
    everything = sorted({name for _, names in groups for name in names})
    lines += ["", "__all__ = [", *(f"    {json.dumps(name)}," for name in everything), "]", ""]
    return "\n".join(lines)


def params_exports() -> list[str]:
    """The literal ``__all__`` of the hand-written ``_params.py``, read without importing it."""
    tree = ast.parse(PARAMS.read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets
        ):
            return sorted(ast.literal_eval(node.value))
    raise SystemExit(f"{PARAMS.relative_to(ROOT)} has no literal __all__")


def webhooks_module(spec: dict[str, Any], core_names: dict[str, str]) -> str:
    lines = [
        HEADER.format(source="openapi/openapi.yaml"),
        '"""The events Kaiten delivers to webhook endpoints, one model per published contract."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Annotated, Literal",
        "",
        "from pydantic import Field",
        "",
        "from .._models import KaitenModel",
    ]

    events: list[tuple[str, str, str, str, str]] = []
    for key, item in sorted((spec.get("webhooks") or {}).items()):
        operation = item["post"]
        schema = operation["requestBody"]["content"]["application/json"]["schema"]
        properties = schema["properties"]
        event_type = only_enum_value(properties["type"], f"webhook {key}.type")
        if event_type != key:
            raise SystemExit(f"webhook {key}: its type enum says {event_type!r}")
        event_name = only_enum_value(properties["name"], f"webhook {key}.name")
        data = core_names[ref_name(properties["data"]["$ref"])]
        python = re.sub(r"^on", "", operation["operationId"]) + "Event"
        summary = operation.get("description") or operation.get("summary") or ""
        events.append((python, event_name, event_type, data, summary))

    data_types = sorted({data for _, _, _, data, _ in events})
    lines.append(f"from ._core import {', '.join(data_types)}")
    lines += ["", "__all__ = [", '    "WEBHOOK_EVENTS",', '    "WebhookEvent",']
    lines += [f'    "{python}",' for python, *_ in sorted(events)]
    lines += ["]", ""]

    for python, event_name, event_type, data, summary in events:
        lines += ["", f"class {python}(KaitenModel):"]
        lines += docstring(f"{summary} Delivered as ``{event_type}``.", "    ")
        lines += [
            "",
            f"    name: Literal[{json.dumps(event_name)}]",
            '    """The event name."""',
            "",
            f"    type: Literal[{json.dumps(event_type)}]",
            '    """The event type: what tells one event from another."""',
            "",
            f"    data: {data}",
            '    """What the event is about."""',
            "",
        ]

    members = "\n".join(f"    | {python}" for python, *_ in events).lstrip(" |")
    lines += [
        "",
        f'WebhookEvent = Annotated[\n    {members},\n    Field(discriminator="type"),\n]',
        '"""Any event Kaiten delivers to a webhook endpoint, discriminated by ``type``."""',
        "",
        "WEBHOOK_EVENTS: dict[str, type[KaitenModel]] = {",
        *(f"    {json.dumps(event_type)}: {python}," for python, _, event_type, _, _ in events),
        "}",
        '"""Every published event type, mapped to the model that parses it."""',
        "",
    ]
    return "\n".join(lines)


class ModelModule:
    """Renders the models of one contract document into one Python module."""

    def __init__(self, *, source: str, schemas: dict[str, Any], names: dict[str, str]) -> None:
        self.source = source
        self.schemas = schemas
        self.names = names
        self.imports: set[str] = set()
        self.enums: dict[str, tuple[Any, ...]] = {}
        self.unions: dict[str, tuple[str | None, list[str]]] = {}
        self.aliases: dict[str, str] = {}
        self.nullable_aliases: set[str] = set()
        self.classes: list[str] = []
        self.body: list[str] = []

    @property
    def exports(self) -> list[str]:
        return sorted({*self.enums, *self.unions, *self.aliases, *self.classes})

    def add_schema(self, name: str) -> None:
        schema = self.schemas[name]
        python = self.names[name]
        if "properties" in schema or schema.get("type") == "object":
            self.classes.append(python)
            self.body += ["", *self.render_class(name, schema), ""]
        elif "oneOf" in schema or "anyOf" in schema:
            self.union(schema, owner=name, name=python)
        else:
            annotation = self.annotation(schema, owner=name, prop=None)
            self.aliases[python] = annotation
            if annotation.endswith("| None"):
                self.nullable_aliases.add(python)

    def render_class(self, name: str, schema: dict[str, Any]) -> list[str]:
        python = self.names[name]
        lines = [f"class {python}(KaitenModel):"]
        lines += docstring(schema.get("description") or CLASS_DOCS.get(python), "    ")

        required = set(schema.get("required") or [])
        properties: dict[str, Any] = schema.get("properties") or {}
        if not properties and len(lines) == 1:
            lines.append("    pass")

        for wire, node in properties.items():
            attribute = FIELD_NAMES.get((name, wire), snake_case(wire))
            if keyword.iskeyword(attribute) or hasattr(BaseModel, attribute):
                raise SystemExit(
                    f"{name}.{wire}: {attribute!r} would shadow a pydantic member; "
                    "give it a name in FIELD_NAMES"
                )

            annotation = self.annotation(node, owner=name, prop=wire)
            if wire in required:
                default = f" = Field(alias={json.dumps(wire)})" if attribute != wire else ""
            else:
                if not self.is_nullable(annotation):
                    annotation += " | None"
                default = (
                    f" = Field(default=None, alias={json.dumps(wire)})"
                    if attribute != wire
                    else " = None"
                )

            lines += ["", f"    {attribute}: {annotation}{default}"]
            lines += docstring(node.get("description"), "    ")
        return lines

    def annotation(self, node: dict[str, Any], *, owner: str, prop: str | None) -> str:
        where = f"{owner}.{prop}" if prop else owner
        if "$ref" in node:
            return self.names[ref_name(node["$ref"])]
        for key in ("oneOf", "anyOf"):
            if key in node:
                return self.union(node, owner=owner)

        kind = node.get("type")
        nullable = False
        if isinstance(kind, list):
            nullable = "null" in kind
            rest = [item for item in kind if item != "null"]
            if len(rest) > 1:
                raise SystemExit(f"{where}: multi-type schemas are not supported ({kind})")
            kind = rest[0] if rest else None

        if kind is None:
            text = "Any"
        elif kind == "string":
            text = self.string(node, owner=owner, prop=prop)
        elif kind == "integer":
            text = "int"
        elif kind == "number":
            text = "float"
        elif kind == "boolean":
            text = "bool"
        elif kind == "array":
            text = f"list[{self.annotation(node.get('items') or {}, owner=owner, prop=prop)}]"
        elif kind == "object":
            if node.get("properties"):
                raise SystemExit(f"{where}: inline object schemas are not supported")
            extra = node.get("additionalProperties")
            value = (
                self.annotation(extra, owner=owner, prop=prop)
                if isinstance(extra, dict) and extra
                else "Any"
            )
            text = f"dict[str, {value}]"
        else:
            raise SystemExit(f"{where}: unsupported schema type {kind!r}")
        return f"{text} | None" if nullable else text

    def string(self, node: dict[str, Any], *, owner: str, prop: str | None) -> str:
        values = node.get("enum")
        if values:
            if len(values) == 1:
                return f"Literal[{json.dumps(values[0])}]"
            name = ENUM_NAMES.get((owner, prop or ""))
            if name is None:
                raise SystemExit(f"{owner}.{prop}: name this enum in ENUM_NAMES ({values})")
            known = self.enums.setdefault(name, tuple(values))
            if known != tuple(values):
                raise SystemExit(f"{name}: {owner}.{prop} has {values}, elsewhere {list(known)}")
            return f"{name} | str"
        if node.get("format") == "date-time":
            return "datetime"
        return "str"

    def union(self, node: dict[str, Any], *, owner: str, name: str | None = None) -> str:
        key = "oneOf" if "oneOf" in node else "anyOf"
        members: list[str] = []
        for member in node[key]:
            if "$ref" not in member:
                raise SystemExit(f"{owner}: inline union members are not supported")
            members.append(ref_name(member["$ref"]))

        name = name or UNION_NAMES.get(frozenset(members))
        if name is None:
            raise SystemExit(f"{owner}: name the union of {members} in UNION_NAMES")
        tag = (node.get("discriminator") or {}).get("propertyName") or self.shared_tag(members)
        self.unions[name] = (tag, [self.names[member] for member in members])
        return name

    def shared_tag(self, members: Iterable[str]) -> str | None:
        """``type``, when every member pins it to its own single value."""
        tags = []
        for member in members:
            enum = (self.schemas[member].get("properties") or {}).get("type", {}).get("enum") or []
            if len(enum) != 1:
                return None
            tags.append(enum[0])
        return "type" if len(set(tags)) == len(tags) else None

    def is_nullable(self, annotation: str) -> bool:
        return annotation.endswith("| None") or annotation in self.nullable_aliases

    def render(self) -> str:
        lines = [
            HEADER.format(source=self.source),
            "from __future__ import annotations",
            "",
            "from datetime import datetime",
            "from typing import Annotated, Any, Literal",
            "",
            "from pydantic import Field",
            "",
            "from .._models import KaitenModel",
        ]
        if self.imports:
            lines.append(f"from ._core import {', '.join(sorted(self.imports))}")
        lines += [
            "",
            "__all__ = [",
            *(f"    {json.dumps(name)}," for name in self.exports),
            "]",
            "",
        ]

        for name, values in sorted(self.enums.items()):
            lines += ["", f"{name} = Literal[{', '.join(json.dumps(value) for value in values)}]"]
            lines += docstring(ALIAS_DOCS.get(name), "")
        lines += self.body

        for name, (tag, members) in sorted(self.unions.items()):
            union = " | ".join(members)
            if tag:
                lines += [
                    "",
                    f"{name} = Annotated[{union}, Field(discriminator={json.dumps(tag)})]",
                ]
            else:
                lines += ["", f"{name} = {union}"]
            lines += docstring(ALIAS_DOCS.get(name), "")
        for name, annotation in sorted(self.aliases.items()):
            lines += ["", f"{name} = {annotation}"]
            lines += docstring(ALIAS_DOCS.get(name), "")

        if self.classes:
            # Annotations are strings under `from __future__ import annotations`, and some name
            # aliases defined after the classes. Resolving them here, once, makes a broken
            # model an import-time error instead of a surprise on the first response it parses.
            lines += ["", "", f"for _model in ({', '.join(self.classes)},):"]
            lines += ["    _model.model_rebuild()", "del _model", ""]
        return "\n".join(lines) + "\n"


def load(path: Path) -> Any:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def refs_in(node: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            found.add(ref_name(ref))
        for value in node.values():
            found |= refs_in(value)
    elif isinstance(node, list):
        for value in node:
            found |= refs_in(value)
    return found


def operations(spec: dict[str, Any]) -> Iterator[dict[str, Any]]:
    for item in spec["paths"].values():
        for method in HTTP_METHODS:
            if method in item:
                yield item[method]


def response_roots(spec: dict[str, Any], excluded: set[str]) -> set[str]:
    roots: set[str] = set()
    for operation in operations(spec):
        if operation["operationId"] in excluded:
            continue
        for response in (operation.get("responses") or {}).values():
            for media in (response.get("content") or {}).values():
                roots |= refs_in(media.get("schema") or {})
    return roots


def closure(schemas: dict[str, Any], roots: Iterable[str]) -> set[str]:
    seen: set[str] = set()
    pending = list(roots)
    while pending:
        name = pending.pop()
        if name not in seen:
            seen.add(name)
            pending.extend(refs_in(schemas[name]) - seen)
    return seen


def without_prose(node: Any) -> Any:
    """The schema minus its documentation, to tell whether two schemas describe one shape."""
    if isinstance(node, dict):
        return {key: without_prose(value) for key, value in node.items() if key not in PROSE}
    if isinstance(node, list):
        return [without_prose(value) for value in node]
    return node


def only_enum_value(node: dict[str, Any], where: str) -> str:
    values = node.get("enum") or []
    if len(values) != 1:
        raise SystemExit(f"{where}: expected a single-value enum, got {values}")
    return str(values[0])


def snake_case(name: str) -> str:
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    return name.replace("-", "_").lower()


def docstring(text: str | None, indent: str) -> list[str]:
    if not text:
        return []
    text = " ".join(text.split()).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    if text.endswith('"'):
        text += " "
    if len(indent) + len(text) + 6 <= 100:
        return [f'{indent}"""{text}"""']
    wrapped = textwrap.wrap(text, width=92 - len(indent))
    return [
        f'{indent}"""{wrapped[0]}',
        *(f"{indent}{line}" for line in wrapped[1:]),
        f'{indent}"""',
    ]


if __name__ == "__main__":
    sys.exit(main())
