#!/usr/bin/env python3
# Copyright 2026 KAITEN INC
# SPDX-License-Identifier: Apache-2.0

"""Generate the synchronous SDK from the asynchronous one.

``src/kaitencloud/_async`` is the only hand-written implementation of the clients and their
resources. ``src/kaitencloud/_sync`` is derived from it token by token, so the two cannot
drift: a fix lands once and reaches both. Usage::

    uv run python scripts/unasync.py          # regenerate src/kaitencloud/_sync
    uv run python scripts/unasync.py --check  # exit 1 when _sync is stale

The rules are few and mechanical, and the async source follows the conventions they rely on:
coroutine helpers are named ``async_*`` (``async_sleep`` becomes ``sleep``), async classes are
named ``Async*``, and prose avoids the words the rules rewrite.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from _codegen import LICENSE_HEADER, ROOT, emit

SOURCE = ROOT / "src" / "kaitencloud" / "_async"
TARGET = ROOT / "src" / "kaitencloud" / "_sync"

HEADER = """\
# Generated by scripts/unasync.py from src/kaitencloud/_async/{path}. Do not edit by hand:
# change the async source, then run `task generate`.
"""

RULES: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\basync def\b"), "def"),
    (re.compile(r"\basync with\b"), "with"),
    (re.compile(r"\basync for\b"), "for"),
    (re.compile(r"\bawait "), ""),
    (re.compile(r"\b__aenter__\b"), "__enter__"),
    (re.compile(r"\b__aexit__\b"), "__exit__"),
    (re.compile(r"\baclose\b"), "close"),
    (re.compile(r"\basync_(\w+)"), r"\1"),
    (re.compile(r"\b_Async(?=[A-Z])"), "_"),
    (re.compile(r"\bAsync(?=[A-Z])"), ""),
    (re.compile(r"\b_async\b"), "_sync"),
]


def unasync(source: str) -> str:
    for pattern, replacement in RULES:
        source = pattern.sub(replacement, source)
    return source


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the synchronous SDK from the async one.")
    parser.add_argument("--check", action="store_true", help="fail when _sync is stale")
    args = parser.parse_args()

    files: dict[Path, str] = {}
    for path in sorted(SOURCE.rglob("*.py")):
        relative = path.relative_to(SOURCE)
        source = path.read_text(encoding="utf-8")
        if not source.startswith(LICENSE_HEADER):
            print(f"{path} does not open with the license header", file=sys.stderr)
            return 1
        body = source.removeprefix(LICENSE_HEADER).lstrip("\n")
        files[TARGET / relative] = (
            LICENSE_HEADER + "\n" + HEADER.format(path=relative.as_posix()) + unasync(body)
        )
    orphans = [path for path in TARGET.rglob("*.py") if path not in files]

    if emit(files, check=args.check, orphans=orphans):
        return 0
    if args.check:
        print("src/kaitencloud/_sync is stale: run `task generate`", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
